=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class MerchantTransactionEntityResponseDataInner
    attr_accessor :transaction_id

    attr_accessor :merchant_id

    attr_accessor :ip_address

    attr_accessor :transaction_date

    attr_accessor :operation_type

    attr_accessor :channel_type

    attr_accessor :process_method

    attr_accessor :is_debit

    attr_accessor :reference_transaction_id

    attr_accessor :reference_customer_id

    attr_accessor :recurring_id

    attr_accessor :batch_id

    attr_accessor :transaction_status

    attr_accessor :settlement_date

    attr_accessor :auth_code

    attr_accessor :card_number

    attr_accessor :account_number

    attr_accessor :bin_number

    attr_accessor :cheque_number

    attr_accessor :routing_number

    attr_accessor :name_on_check_or_card

    attr_accessor :account_holder_name

    attr_accessor :account_category

    attr_accessor :training_mode

    attr_accessor :amount

    attr_accessor :convenience_amount

    attr_accessor :capture_amount

    attr_accessor :card_type

    attr_accessor :created_on

    attr_accessor :created_by

    attr_accessor :modified_on

    attr_accessor :modified_by

    attr_accessor :customer_name

    attr_accessor :partner_id

    attr_accessor :partner_name

    attr_accessor :order_id

    attr_accessor :invoice_id

    attr_accessor :payment_link_id

    attr_accessor :reference_no

    attr_accessor :processor_name

    attr_accessor :processor_display_name

    attr_accessor :verification2_code

    attr_accessor :transaction_origin

    attr_accessor :previous_transaction_status

    attr_accessor :trace_number

    attr_accessor :merchant_reference

    attr_accessor :additiona_fields

    attr_accessor :adjustment_value

    attr_accessor :adjustment_fixed_value

    attr_accessor :adjustment_amount

    attr_accessor :adjustment_display_name

    attr_accessor :adjustment_descriptor_message

    attr_accessor :payment_adjustment_type

    attr_accessor :commission_type

    attr_accessor :commission_value

    attr_accessor :commission_fixed_value

    attr_accessor :account_token

    attr_accessor :payment_type

    attr_accessor :payment_category

    attr_accessor :refund_reason

    attr_accessor :refund_detail

    attr_accessor :full_account_number

    attr_accessor :refund_type

    attr_accessor :suppress_technology_fee

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'transaction_id' => :'transactionId',
        :'merchant_id' => :'merchantId',
        :'ip_address' => :'ipAddress',
        :'transaction_date' => :'transactionDate',
        :'operation_type' => :'operationType',
        :'channel_type' => :'channelType',
        :'process_method' => :'processMethod',
        :'is_debit' => :'isDebit',
        :'reference_transaction_id' => :'referenceTransactionId',
        :'reference_customer_id' => :'referenceCustomerId',
        :'recurring_id' => :'recurringId',
        :'batch_id' => :'batchId',
        :'transaction_status' => :'transactionStatus',
        :'settlement_date' => :'settlementDate',
        :'auth_code' => :'authCode',
        :'card_number' => :'cardNumber',
        :'account_number' => :'accountNumber',
        :'bin_number' => :'binNumber',
        :'cheque_number' => :'chequeNumber',
        :'routing_number' => :'routingNumber',
        :'name_on_check_or_card' => :'nameOnCheckOrCard',
        :'account_holder_name' => :'accountHolderName',
        :'account_category' => :'accountCategory',
        :'training_mode' => :'trainingMode',
        :'amount' => :'amount',
        :'convenience_amount' => :'convenienceAmount',
        :'capture_amount' => :'captureAmount',
        :'card_type' => :'cardType',
        :'created_on' => :'createdOn',
        :'created_by' => :'createdBy',
        :'modified_on' => :'modifiedOn',
        :'modified_by' => :'modifiedBy',
        :'customer_name' => :'customerName',
        :'partner_id' => :'partnerId',
        :'partner_name' => :'partnerName',
        :'order_id' => :'orderId',
        :'invoice_id' => :'invoiceId',
        :'payment_link_id' => :'paymentLinkId',
        :'reference_no' => :'referenceNo',
        :'processor_name' => :'processorName',
        :'processor_display_name' => :'processorDisplayName',
        :'verification2_code' => :'verification2Code',
        :'transaction_origin' => :'transactionOrigin',
        :'previous_transaction_status' => :'previousTransactionStatus',
        :'trace_number' => :'traceNumber',
        :'merchant_reference' => :'merchantReference',
        :'additiona_fields' => :'additionaFields',
        :'adjustment_value' => :'adjustmentValue',
        :'adjustment_fixed_value' => :'adjustmentFixedValue',
        :'adjustment_amount' => :'adjustmentAmount',
        :'adjustment_display_name' => :'adjustmentDisplayName',
        :'adjustment_descriptor_message' => :'adjustmentDescriptorMessage',
        :'payment_adjustment_type' => :'paymentAdjustmentType',
        :'commission_type' => :'commissionType',
        :'commission_value' => :'commissionValue',
        :'commission_fixed_value' => :'commissionFixedValue',
        :'account_token' => :'accountToken',
        :'payment_type' => :'paymentType',
        :'payment_category' => :'paymentCategory',
        :'refund_reason' => :'refundReason',
        :'refund_detail' => :'refundDetail',
        :'full_account_number' => :'fullAccountNumber',
        :'refund_type' => :'refundType',
        :'suppress_technology_fee' => :'suppressTechnologyFee'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'transaction_id' => :'String',
        :'merchant_id' => :'String',
        :'ip_address' => :'String',
        :'transaction_date' => :'String',
        :'operation_type' => :'String',
        :'channel_type' => :'String',
        :'process_method' => :'String',
        :'is_debit' => :'Boolean',
        :'reference_transaction_id' => :'String',
        :'reference_customer_id' => :'String',
        :'recurring_id' => :'String',
        :'batch_id' => :'Float',
        :'transaction_status' => :'String',
        :'settlement_date' => :'String',
        :'auth_code' => :'String',
        :'card_number' => :'String',
        :'account_number' => :'String',
        :'bin_number' => :'String',
        :'cheque_number' => :'String',
        :'routing_number' => :'String',
        :'name_on_check_or_card' => :'String',
        :'account_holder_name' => :'String',
        :'account_category' => :'String',
        :'training_mode' => :'Boolean',
        :'amount' => :'Float',
        :'convenience_amount' => :'Float',
        :'capture_amount' => :'Float',
        :'card_type' => :'String',
        :'created_on' => :'String',
        :'created_by' => :'String',
        :'modified_on' => :'String',
        :'modified_by' => :'String',
        :'customer_name' => :'String',
        :'partner_id' => :'String',
        :'partner_name' => :'String',
        :'order_id' => :'String',
        :'invoice_id' => :'String',
        :'payment_link_id' => :'String',
        :'reference_no' => :'String',
        :'processor_name' => :'String',
        :'processor_display_name' => :'String',
        :'verification2_code' => :'String',
        :'transaction_origin' => :'String',
        :'previous_transaction_status' => :'String',
        :'trace_number' => :'String',
        :'merchant_reference' => :'String',
        :'additiona_fields' => :'String',
        :'adjustment_value' => :'Float',
        :'adjustment_fixed_value' => :'Float',
        :'adjustment_amount' => :'Float',
        :'adjustment_display_name' => :'String',
        :'adjustment_descriptor_message' => :'String',
        :'payment_adjustment_type' => :'String',
        :'commission_type' => :'TransactionPaymentResponseAchTenderInfoCommissionType',
        :'commission_value' => :'Float',
        :'commission_fixed_value' => :'Float',
        :'account_token' => :'String',
        :'payment_type' => :'String',
        :'payment_category' => :'String',
        :'refund_reason' => :'String',
        :'refund_detail' => :'String',
        :'full_account_number' => :'String',
        :'refund_type' => :'String',
        :'suppress_technology_fee' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::MerchantTransactionEntityResponseDataInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::MerchantTransactionEntityResponseDataInner`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'transaction_id')
        self.transaction_id = attributes[:'transaction_id']
      end

      if attributes.key?(:'merchant_id')
        self.merchant_id = attributes[:'merchant_id']
      end

      if attributes.key?(:'ip_address')
        self.ip_address = attributes[:'ip_address']
      end

      if attributes.key?(:'transaction_date')
        self.transaction_date = attributes[:'transaction_date']
      end

      if attributes.key?(:'operation_type')
        self.operation_type = attributes[:'operation_type']
      end

      if attributes.key?(:'channel_type')
        self.channel_type = attributes[:'channel_type']
      end

      if attributes.key?(:'process_method')
        self.process_method = attributes[:'process_method']
      end

      if attributes.key?(:'is_debit')
        self.is_debit = attributes[:'is_debit']
      end

      if attributes.key?(:'reference_transaction_id')
        self.reference_transaction_id = attributes[:'reference_transaction_id']
      end

      if attributes.key?(:'reference_customer_id')
        self.reference_customer_id = attributes[:'reference_customer_id']
      end

      if attributes.key?(:'recurring_id')
        self.recurring_id = attributes[:'recurring_id']
      end

      if attributes.key?(:'batch_id')
        self.batch_id = attributes[:'batch_id']
      end

      if attributes.key?(:'transaction_status')
        self.transaction_status = attributes[:'transaction_status']
      end

      if attributes.key?(:'settlement_date')
        self.settlement_date = attributes[:'settlement_date']
      end

      if attributes.key?(:'auth_code')
        self.auth_code = attributes[:'auth_code']
      end

      if attributes.key?(:'card_number')
        self.card_number = attributes[:'card_number']
      end

      if attributes.key?(:'account_number')
        self.account_number = attributes[:'account_number']
      end

      if attributes.key?(:'bin_number')
        self.bin_number = attributes[:'bin_number']
      end

      if attributes.key?(:'cheque_number')
        self.cheque_number = attributes[:'cheque_number']
      end

      if attributes.key?(:'routing_number')
        self.routing_number = attributes[:'routing_number']
      end

      if attributes.key?(:'name_on_check_or_card')
        self.name_on_check_or_card = attributes[:'name_on_check_or_card']
      end

      if attributes.key?(:'account_holder_name')
        self.account_holder_name = attributes[:'account_holder_name']
      end

      if attributes.key?(:'account_category')
        self.account_category = attributes[:'account_category']
      end

      if attributes.key?(:'training_mode')
        self.training_mode = attributes[:'training_mode']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'convenience_amount')
        self.convenience_amount = attributes[:'convenience_amount']
      end

      if attributes.key?(:'capture_amount')
        self.capture_amount = attributes[:'capture_amount']
      end

      if attributes.key?(:'card_type')
        self.card_type = attributes[:'card_type']
      end

      if attributes.key?(:'created_on')
        self.created_on = attributes[:'created_on']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'modified_on')
        self.modified_on = attributes[:'modified_on']
      end

      if attributes.key?(:'modified_by')
        self.modified_by = attributes[:'modified_by']
      end

      if attributes.key?(:'customer_name')
        self.customer_name = attributes[:'customer_name']
      end

      if attributes.key?(:'partner_id')
        self.partner_id = attributes[:'partner_id']
      end

      if attributes.key?(:'partner_name')
        self.partner_name = attributes[:'partner_name']
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.key?(:'invoice_id')
        self.invoice_id = attributes[:'invoice_id']
      end

      if attributes.key?(:'payment_link_id')
        self.payment_link_id = attributes[:'payment_link_id']
      end

      if attributes.key?(:'reference_no')
        self.reference_no = attributes[:'reference_no']
      end

      if attributes.key?(:'processor_name')
        self.processor_name = attributes[:'processor_name']
      end

      if attributes.key?(:'processor_display_name')
        self.processor_display_name = attributes[:'processor_display_name']
      end

      if attributes.key?(:'verification2_code')
        self.verification2_code = attributes[:'verification2_code']
      end

      if attributes.key?(:'transaction_origin')
        self.transaction_origin = attributes[:'transaction_origin']
      end

      if attributes.key?(:'previous_transaction_status')
        self.previous_transaction_status = attributes[:'previous_transaction_status']
      end

      if attributes.key?(:'trace_number')
        self.trace_number = attributes[:'trace_number']
      end

      if attributes.key?(:'merchant_reference')
        self.merchant_reference = attributes[:'merchant_reference']
      end

      if attributes.key?(:'additiona_fields')
        self.additiona_fields = attributes[:'additiona_fields']
      end

      if attributes.key?(:'adjustment_value')
        self.adjustment_value = attributes[:'adjustment_value']
      end

      if attributes.key?(:'adjustment_fixed_value')
        self.adjustment_fixed_value = attributes[:'adjustment_fixed_value']
      end

      if attributes.key?(:'adjustment_amount')
        self.adjustment_amount = attributes[:'adjustment_amount']
      end

      if attributes.key?(:'adjustment_display_name')
        self.adjustment_display_name = attributes[:'adjustment_display_name']
      end

      if attributes.key?(:'adjustment_descriptor_message')
        self.adjustment_descriptor_message = attributes[:'adjustment_descriptor_message']
      end

      if attributes.key?(:'payment_adjustment_type')
        self.payment_adjustment_type = attributes[:'payment_adjustment_type']
      end

      if attributes.key?(:'commission_type')
        self.commission_type = attributes[:'commission_type']
      end

      if attributes.key?(:'commission_value')
        self.commission_value = attributes[:'commission_value']
      end

      if attributes.key?(:'commission_fixed_value')
        self.commission_fixed_value = attributes[:'commission_fixed_value']
      end

      if attributes.key?(:'account_token')
        self.account_token = attributes[:'account_token']
      end

      if attributes.key?(:'payment_type')
        self.payment_type = attributes[:'payment_type']
      end

      if attributes.key?(:'payment_category')
        self.payment_category = attributes[:'payment_category']
      end

      if attributes.key?(:'refund_reason')
        self.refund_reason = attributes[:'refund_reason']
      end

      if attributes.key?(:'refund_detail')
        self.refund_detail = attributes[:'refund_detail']
      end

      if attributes.key?(:'full_account_number')
        self.full_account_number = attributes[:'full_account_number']
      end

      if attributes.key?(:'refund_type')
        self.refund_type = attributes[:'refund_type']
      end

      if attributes.key?(:'suppress_technology_fee')
        self.suppress_technology_fee = attributes[:'suppress_technology_fee']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      operation_type_validator = EnumAttributeValidator.new('String', ["Sale", "VerifyOnly", "ForceSale", "Adjust", "Activate", "Deactivate", "Reload", "Refund", "Inquire", "ReverseAuth"])
      return false unless operation_type_validator.valid?(@operation_type)
      channel_type_validator = EnumAttributeValidator.new('String', ["NotDefined", "ACH", "CreditCard", "DebitCard"])
      return false unless channel_type_validator.valid?(@channel_type)
      process_method_validator = EnumAttributeValidator.new('String', ["NotDefined", "ACH", "CardNotPresent"])
      return false unless process_method_validator.valid?(@process_method)
      transaction_status_validator = EnumAttributeValidator.new('String', ["Created", "PendingForAuthorized", "Authorized", "Posted", "Captured", "Failed", "Returned", "Chargeback", "Cancelled", "Refunded", "Approved", "CancelAttempt", "RefundAttempt", "Hold", "Denied", "SettlementHold", "Success", "Retried", "ReprocessAttempt", "Reprocessed", "ChargebackReversed", "RefundedReversed", "Paid", "PaidChargeback", "PaidChargebackReversed", "PaidRefunded", "PaidRefundedReversed", "None", "Unknown"])
      return false unless transaction_status_validator.valid?(@transaction_status)
      account_category_validator = EnumAttributeValidator.new('String', ["Unknown", "Personal", "Business"])
      return false unless account_category_validator.valid?(@account_category)
      transaction_origin_validator = EnumAttributeValidator.new('String', ["Terminal", "VirtualTerminal", "WebForm", "API", "Schedule", "Batch", "PaymentIntent"])
      return false unless transaction_origin_validator.valid?(@transaction_origin)
      previous_transaction_status_validator = EnumAttributeValidator.new('String', ["Created", "PendingForAuthorized", "Authorized", "Posted", "Captured", "Failed", "Returned", "Chargeback", "Cancelled", "Refunded", "Approved", "CancelAttempt", "RefundAttempt", "Hold", "Denied", "SettlementHold", "Success", "Retried", "ReprocessAttempt", "Reprocessed", "ChargebackReversed", "RefundedReversed", "Paid", "PaidChargeback", "PaidChargebackReversed", "PaidRefunded", "PaidRefundedReversed", "None", "Unknown"])
      return false unless previous_transaction_status_validator.valid?(@previous_transaction_status)
      payment_adjustment_type_validator = EnumAttributeValidator.new('String', ["None", "CashIncentive", "Surcharge", "ConvenienceFee", "CashDiscount"])
      return false unless payment_adjustment_type_validator.valid?(@payment_adjustment_type)
      payment_type_validator = EnumAttributeValidator.new('String', ["None", "AnytimePayment", "SubDomain", "PaymentIntent", "PaymentLink", "OpenPayment", "TokenLink"])
      return false unless payment_type_validator.valid?(@payment_type)
      payment_category_validator = EnumAttributeValidator.new('String', ["None", "MerchantPayment", "MPIPD", "MPIPI", "PFD", "PFI"])
      return false unless payment_category_validator.valid?(@payment_category)
      refund_type_validator = EnumAttributeValidator.new('String', ["NA", "Total", "Subtotal", "Remaining", "Partial"])
      return false unless refund_type_validator.valid?(@refund_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] operation_type Object to be assigned
    def operation_type=(operation_type)
      validator = EnumAttributeValidator.new('String', ["Sale", "VerifyOnly", "ForceSale", "Adjust", "Activate", "Deactivate", "Reload", "Refund", "Inquire", "ReverseAuth"])
      unless validator.valid?(operation_type)
        fail ArgumentError, "invalid value for \"operation_type\", must be one of #{validator.allowable_values}."
      end
      @operation_type = operation_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] channel_type Object to be assigned
    def channel_type=(channel_type)
      validator = EnumAttributeValidator.new('String', ["NotDefined", "ACH", "CreditCard", "DebitCard"])
      unless validator.valid?(channel_type)
        fail ArgumentError, "invalid value for \"channel_type\", must be one of #{validator.allowable_values}."
      end
      @channel_type = channel_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] process_method Object to be assigned
    def process_method=(process_method)
      validator = EnumAttributeValidator.new('String', ["NotDefined", "ACH", "CardNotPresent"])
      unless validator.valid?(process_method)
        fail ArgumentError, "invalid value for \"process_method\", must be one of #{validator.allowable_values}."
      end
      @process_method = process_method
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] transaction_status Object to be assigned
    def transaction_status=(transaction_status)
      validator = EnumAttributeValidator.new('String', ["Created", "PendingForAuthorized", "Authorized", "Posted", "Captured", "Failed", "Returned", "Chargeback", "Cancelled", "Refunded", "Approved", "CancelAttempt", "RefundAttempt", "Hold", "Denied", "SettlementHold", "Success", "Retried", "ReprocessAttempt", "Reprocessed", "ChargebackReversed", "RefundedReversed", "Paid", "PaidChargeback", "PaidChargebackReversed", "PaidRefunded", "PaidRefundedReversed", "None", "Unknown"])
      unless validator.valid?(transaction_status)
        fail ArgumentError, "invalid value for \"transaction_status\", must be one of #{validator.allowable_values}."
      end
      @transaction_status = transaction_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] account_category Object to be assigned
    def account_category=(account_category)
      validator = EnumAttributeValidator.new('String', ["Unknown", "Personal", "Business"])
      unless validator.valid?(account_category)
        fail ArgumentError, "invalid value for \"account_category\", must be one of #{validator.allowable_values}."
      end
      @account_category = account_category
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] transaction_origin Object to be assigned
    def transaction_origin=(transaction_origin)
      validator = EnumAttributeValidator.new('String', ["Terminal", "VirtualTerminal", "WebForm", "API", "Schedule", "Batch", "PaymentIntent"])
      unless validator.valid?(transaction_origin)
        fail ArgumentError, "invalid value for \"transaction_origin\", must be one of #{validator.allowable_values}."
      end
      @transaction_origin = transaction_origin
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] previous_transaction_status Object to be assigned
    def previous_transaction_status=(previous_transaction_status)
      validator = EnumAttributeValidator.new('String', ["Created", "PendingForAuthorized", "Authorized", "Posted", "Captured", "Failed", "Returned", "Chargeback", "Cancelled", "Refunded", "Approved", "CancelAttempt", "RefundAttempt", "Hold", "Denied", "SettlementHold", "Success", "Retried", "ReprocessAttempt", "Reprocessed", "ChargebackReversed", "RefundedReversed", "Paid", "PaidChargeback", "PaidChargebackReversed", "PaidRefunded", "PaidRefundedReversed", "None", "Unknown"])
      unless validator.valid?(previous_transaction_status)
        fail ArgumentError, "invalid value for \"previous_transaction_status\", must be one of #{validator.allowable_values}."
      end
      @previous_transaction_status = previous_transaction_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] payment_adjustment_type Object to be assigned
    def payment_adjustment_type=(payment_adjustment_type)
      validator = EnumAttributeValidator.new('String', ["None", "CashIncentive", "Surcharge", "ConvenienceFee", "CashDiscount"])
      unless validator.valid?(payment_adjustment_type)
        fail ArgumentError, "invalid value for \"payment_adjustment_type\", must be one of #{validator.allowable_values}."
      end
      @payment_adjustment_type = payment_adjustment_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] payment_type Object to be assigned
    def payment_type=(payment_type)
      validator = EnumAttributeValidator.new('String', ["None", "AnytimePayment", "SubDomain", "PaymentIntent", "PaymentLink", "OpenPayment", "TokenLink"])
      unless validator.valid?(payment_type)
        fail ArgumentError, "invalid value for \"payment_type\", must be one of #{validator.allowable_values}."
      end
      @payment_type = payment_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] payment_category Object to be assigned
    def payment_category=(payment_category)
      validator = EnumAttributeValidator.new('String', ["None", "MerchantPayment", "MPIPD", "MPIPI", "PFD", "PFI"])
      unless validator.valid?(payment_category)
        fail ArgumentError, "invalid value for \"payment_category\", must be one of #{validator.allowable_values}."
      end
      @payment_category = payment_category
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] refund_type Object to be assigned
    def refund_type=(refund_type)
      validator = EnumAttributeValidator.new('String', ["NA", "Total", "Subtotal", "Remaining", "Partial"])
      unless validator.valid?(refund_type)
        fail ArgumentError, "invalid value for \"refund_type\", must be one of #{validator.allowable_values}."
      end
      @refund_type = refund_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          transaction_id == o.transaction_id &&
          merchant_id == o.merchant_id &&
          ip_address == o.ip_address &&
          transaction_date == o.transaction_date &&
          operation_type == o.operation_type &&
          channel_type == o.channel_type &&
          process_method == o.process_method &&
          is_debit == o.is_debit &&
          reference_transaction_id == o.reference_transaction_id &&
          reference_customer_id == o.reference_customer_id &&
          recurring_id == o.recurring_id &&
          batch_id == o.batch_id &&
          transaction_status == o.transaction_status &&
          settlement_date == o.settlement_date &&
          auth_code == o.auth_code &&
          card_number == o.card_number &&
          account_number == o.account_number &&
          bin_number == o.bin_number &&
          cheque_number == o.cheque_number &&
          routing_number == o.routing_number &&
          name_on_check_or_card == o.name_on_check_or_card &&
          account_holder_name == o.account_holder_name &&
          account_category == o.account_category &&
          training_mode == o.training_mode &&
          amount == o.amount &&
          convenience_amount == o.convenience_amount &&
          capture_amount == o.capture_amount &&
          card_type == o.card_type &&
          created_on == o.created_on &&
          created_by == o.created_by &&
          modified_on == o.modified_on &&
          modified_by == o.modified_by &&
          customer_name == o.customer_name &&
          partner_id == o.partner_id &&
          partner_name == o.partner_name &&
          order_id == o.order_id &&
          invoice_id == o.invoice_id &&
          payment_link_id == o.payment_link_id &&
          reference_no == o.reference_no &&
          processor_name == o.processor_name &&
          processor_display_name == o.processor_display_name &&
          verification2_code == o.verification2_code &&
          transaction_origin == o.transaction_origin &&
          previous_transaction_status == o.previous_transaction_status &&
          trace_number == o.trace_number &&
          merchant_reference == o.merchant_reference &&
          additiona_fields == o.additiona_fields &&
          adjustment_value == o.adjustment_value &&
          adjustment_fixed_value == o.adjustment_fixed_value &&
          adjustment_amount == o.adjustment_amount &&
          adjustment_display_name == o.adjustment_display_name &&
          adjustment_descriptor_message == o.adjustment_descriptor_message &&
          payment_adjustment_type == o.payment_adjustment_type &&
          commission_type == o.commission_type &&
          commission_value == o.commission_value &&
          commission_fixed_value == o.commission_fixed_value &&
          account_token == o.account_token &&
          payment_type == o.payment_type &&
          payment_category == o.payment_category &&
          refund_reason == o.refund_reason &&
          refund_detail == o.refund_detail &&
          full_account_number == o.full_account_number &&
          refund_type == o.refund_type &&
          suppress_technology_fee == o.suppress_technology_fee
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [transaction_id, merchant_id, ip_address, transaction_date, operation_type, channel_type, process_method, is_debit, reference_transaction_id, reference_customer_id, recurring_id, batch_id, transaction_status, settlement_date, auth_code, card_number, account_number, bin_number, cheque_number, routing_number, name_on_check_or_card, account_holder_name, account_category, training_mode, amount, convenience_amount, capture_amount, card_type, created_on, created_by, modified_on, modified_by, customer_name, partner_id, partner_name, order_id, invoice_id, payment_link_id, reference_no, processor_name, processor_display_name, verification2_code, transaction_origin, previous_transaction_status, trace_number, merchant_reference, additiona_fields, adjustment_value, adjustment_fixed_value, adjustment_amount, adjustment_display_name, adjustment_descriptor_message, payment_adjustment_type, commission_type, commission_value, commission_fixed_value, account_token, payment_type, payment_category, refund_reason, refund_detail, full_account_number, refund_type, suppress_technology_fee].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
