=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PaymentLinkResponse
    attr_accessor :id

    attr_accessor :merchant_id

    attr_accessor :title

    attr_accessor :payment_link

    attr_accessor :short_link

    attr_accessor :amount

    attr_accessor :payment_description

    attr_accessor :expire_in

    attr_accessor :expire_in_unit

    attr_accessor :expire_on

    attr_accessor :payments

    attr_accessor :no_of_payment_made

    attr_accessor :total_paid_amount

    attr_accessor :link_status

    attr_accessor :invoice_number

    attr_accessor :created_on

    attr_accessor :created_by

    attr_accessor :modified_on

    attr_accessor :modified_by

    attr_accessor :short_description

    attr_accessor :response_type

    attr_accessor :callback_parameters

    attr_accessor :customers

    attr_accessor :line_items

    attr_accessor :display_settings

    attr_accessor :splits

    attr_accessor :save_for_future

    attr_accessor :quote_key

    attr_accessor :account_number

    attr_accessor :reference_type

    attr_accessor :reference_number

    attr_accessor :reference_key

    attr_accessor :reference_data_list

    attr_accessor :enable_premium_finance

    attr_accessor :is_premium_financier

    attr_accessor :pfr

    attr_accessor :payment_link_type

    attr_accessor :suppress_technology_fee

    attr_accessor :override_technology_fee

    attr_accessor :is_pf_lite

    attr_accessor :is_pay_in_full

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'merchant_id' => :'merchantId',
        :'title' => :'title',
        :'payment_link' => :'paymentLink',
        :'short_link' => :'shortLink',
        :'amount' => :'amount',
        :'payment_description' => :'paymentDescription',
        :'expire_in' => :'expireIn',
        :'expire_in_unit' => :'expireInUnit',
        :'expire_on' => :'expireOn',
        :'payments' => :'payments',
        :'no_of_payment_made' => :'noOfPaymentMade',
        :'total_paid_amount' => :'totalPaidAmount',
        :'link_status' => :'linkStatus',
        :'invoice_number' => :'invoiceNumber',
        :'created_on' => :'createdOn',
        :'created_by' => :'createdBy',
        :'modified_on' => :'modifiedOn',
        :'modified_by' => :'modifiedBy',
        :'short_description' => :'shortDescription',
        :'response_type' => :'responseType',
        :'callback_parameters' => :'callbackParameters',
        :'customers' => :'customers',
        :'line_items' => :'lineItems',
        :'display_settings' => :'displaySettings',
        :'splits' => :'splits',
        :'save_for_future' => :'saveForFuture',
        :'quote_key' => :'quoteKey',
        :'account_number' => :'accountNumber',
        :'reference_type' => :'referenceType',
        :'reference_number' => :'referenceNumber',
        :'reference_key' => :'referenceKey',
        :'reference_data_list' => :'referenceDataList',
        :'enable_premium_finance' => :'enablePremiumFinance',
        :'is_premium_financier' => :'isPremiumFinancier',
        :'pfr' => :'pfr',
        :'payment_link_type' => :'paymentLinkType',
        :'suppress_technology_fee' => :'suppressTechnologyFee',
        :'override_technology_fee' => :'overrideTechnologyFee',
        :'is_pf_lite' => :'isPFLite',
        :'is_pay_in_full' => :'isPayInFull'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'merchant_id' => :'String',
        :'title' => :'String',
        :'payment_link' => :'String',
        :'short_link' => :'String',
        :'amount' => :'Float',
        :'payment_description' => :'String',
        :'expire_in' => :'Integer',
        :'expire_in_unit' => :'String',
        :'expire_on' => :'String',
        :'payments' => :'Array<PaymentLinkResponsePaymentsInner>',
        :'no_of_payment_made' => :'Float',
        :'total_paid_amount' => :'Float',
        :'link_status' => :'String',
        :'invoice_number' => :'String',
        :'created_on' => :'String',
        :'created_by' => :'String',
        :'modified_on' => :'String',
        :'modified_by' => :'String',
        :'short_description' => :'String',
        :'response_type' => :'String',
        :'callback_parameters' => :'PaymentLinkResponseCallbackParameters',
        :'customers' => :'Array<PaymentLinkResponseCustomersInner>',
        :'line_items' => :'Array<PaymentLinkResponseLineItemsInner>',
        :'display_settings' => :'PaymentLinkResponseDisplaySettings',
        :'splits' => :'Array<PaymentIntentRequestSplitsInner>',
        :'save_for_future' => :'Boolean',
        :'quote_key' => :'String',
        :'account_number' => :'String',
        :'reference_type' => :'String',
        :'reference_number' => :'String',
        :'reference_key' => :'String',
        :'reference_data_list' => :'Array<PaymentLinkResponseReferenceDataListInner>',
        :'enable_premium_finance' => :'Boolean',
        :'is_premium_financier' => :'Boolean',
        :'pfr' => :'PaymentIntentRequestPfr',
        :'payment_link_type' => :'String',
        :'suppress_technology_fee' => :'Boolean',
        :'override_technology_fee' => :'Float',
        :'is_pf_lite' => :'Boolean',
        :'is_pay_in_full' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PaymentLinkResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PaymentLinkResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'merchant_id')
        self.merchant_id = attributes[:'merchant_id']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'payment_link')
        self.payment_link = attributes[:'payment_link']
      end

      if attributes.key?(:'short_link')
        self.short_link = attributes[:'short_link']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'payment_description')
        self.payment_description = attributes[:'payment_description']
      end

      if attributes.key?(:'expire_in')
        self.expire_in = attributes[:'expire_in']
      end

      if attributes.key?(:'expire_in_unit')
        self.expire_in_unit = attributes[:'expire_in_unit']
      end

      if attributes.key?(:'expire_on')
        self.expire_on = attributes[:'expire_on']
      end

      if attributes.key?(:'payments')
        if (value = attributes[:'payments']).is_a?(Array)
          self.payments = value
        end
      end

      if attributes.key?(:'no_of_payment_made')
        self.no_of_payment_made = attributes[:'no_of_payment_made']
      end

      if attributes.key?(:'total_paid_amount')
        self.total_paid_amount = attributes[:'total_paid_amount']
      end

      if attributes.key?(:'link_status')
        self.link_status = attributes[:'link_status']
      end

      if attributes.key?(:'invoice_number')
        self.invoice_number = attributes[:'invoice_number']
      end

      if attributes.key?(:'created_on')
        self.created_on = attributes[:'created_on']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'modified_on')
        self.modified_on = attributes[:'modified_on']
      end

      if attributes.key?(:'modified_by')
        self.modified_by = attributes[:'modified_by']
      end

      if attributes.key?(:'short_description')
        self.short_description = attributes[:'short_description']
      end

      if attributes.key?(:'response_type')
        self.response_type = attributes[:'response_type']
      end

      if attributes.key?(:'callback_parameters')
        self.callback_parameters = attributes[:'callback_parameters']
      end

      if attributes.key?(:'customers')
        if (value = attributes[:'customers']).is_a?(Array)
          self.customers = value
        end
      end

      if attributes.key?(:'line_items')
        if (value = attributes[:'line_items']).is_a?(Array)
          self.line_items = value
        end
      end

      if attributes.key?(:'display_settings')
        self.display_settings = attributes[:'display_settings']
      end

      if attributes.key?(:'splits')
        if (value = attributes[:'splits']).is_a?(Array)
          self.splits = value
        end
      end

      if attributes.key?(:'save_for_future')
        self.save_for_future = attributes[:'save_for_future']
      end

      if attributes.key?(:'quote_key')
        self.quote_key = attributes[:'quote_key']
      end

      if attributes.key?(:'account_number')
        self.account_number = attributes[:'account_number']
      end

      if attributes.key?(:'reference_type')
        self.reference_type = attributes[:'reference_type']
      end

      if attributes.key?(:'reference_number')
        self.reference_number = attributes[:'reference_number']
      end

      if attributes.key?(:'reference_key')
        self.reference_key = attributes[:'reference_key']
      end

      if attributes.key?(:'reference_data_list')
        if (value = attributes[:'reference_data_list']).is_a?(Array)
          self.reference_data_list = value
        end
      end

      if attributes.key?(:'enable_premium_finance')
        self.enable_premium_finance = attributes[:'enable_premium_finance']
      end

      if attributes.key?(:'is_premium_financier')
        self.is_premium_financier = attributes[:'is_premium_financier']
      end

      if attributes.key?(:'pfr')
        self.pfr = attributes[:'pfr']
      end

      if attributes.key?(:'payment_link_type')
        self.payment_link_type = attributes[:'payment_link_type']
      end

      if attributes.key?(:'suppress_technology_fee')
        self.suppress_technology_fee = attributes[:'suppress_technology_fee']
      end

      if attributes.key?(:'override_technology_fee')
        self.override_technology_fee = attributes[:'override_technology_fee']
      end

      if attributes.key?(:'is_pf_lite')
        self.is_pf_lite = attributes[:'is_pf_lite']
      end

      if attributes.key?(:'is_pay_in_full')
        self.is_pay_in_full = attributes[:'is_pay_in_full']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      expire_in_unit_validator = EnumAttributeValidator.new('String', ["Seconds", "Minutes", "Hours", "Days", "Weeks"])
      return false unless expire_in_unit_validator.valid?(@expire_in_unit)
      link_status_validator = EnumAttributeValidator.new('String', ["Created", "Enabled", "Disabled", "Expired", "Paid", "PaymentInitiated", "None"])
      return false unless link_status_validator.valid?(@link_status)
      response_type_validator = EnumAttributeValidator.new('String', ["OnScreen", "CallBack"])
      return false unless response_type_validator.valid?(@response_type)
      reference_type_validator = EnumAttributeValidator.new('String', ["None", "QuoteId", "AccountNumber", "PolicyNumber", "InvoiceNumber", "Other"])
      return false unless reference_type_validator.valid?(@reference_type)
      payment_link_type_validator = EnumAttributeValidator.new('String', ["NA", "PaymentLink", "PaymentIntent", "TokenLink", "Invoice"])
      return false unless payment_link_type_validator.valid?(@payment_link_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] expire_in_unit Object to be assigned
    def expire_in_unit=(expire_in_unit)
      validator = EnumAttributeValidator.new('String', ["Seconds", "Minutes", "Hours", "Days", "Weeks"])
      unless validator.valid?(expire_in_unit)
        fail ArgumentError, "invalid value for \"expire_in_unit\", must be one of #{validator.allowable_values}."
      end
      @expire_in_unit = expire_in_unit
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] link_status Object to be assigned
    def link_status=(link_status)
      validator = EnumAttributeValidator.new('String', ["Created", "Enabled", "Disabled", "Expired", "Paid", "PaymentInitiated", "None"])
      unless validator.valid?(link_status)
        fail ArgumentError, "invalid value for \"link_status\", must be one of #{validator.allowable_values}."
      end
      @link_status = link_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] response_type Object to be assigned
    def response_type=(response_type)
      validator = EnumAttributeValidator.new('String', ["OnScreen", "CallBack"])
      unless validator.valid?(response_type)
        fail ArgumentError, "invalid value for \"response_type\", must be one of #{validator.allowable_values}."
      end
      @response_type = response_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] reference_type Object to be assigned
    def reference_type=(reference_type)
      validator = EnumAttributeValidator.new('String', ["None", "QuoteId", "AccountNumber", "PolicyNumber", "InvoiceNumber", "Other"])
      unless validator.valid?(reference_type)
        fail ArgumentError, "invalid value for \"reference_type\", must be one of #{validator.allowable_values}."
      end
      @reference_type = reference_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] payment_link_type Object to be assigned
    def payment_link_type=(payment_link_type)
      validator = EnumAttributeValidator.new('String', ["NA", "PaymentLink", "PaymentIntent", "TokenLink", "Invoice"])
      unless validator.valid?(payment_link_type)
        fail ArgumentError, "invalid value for \"payment_link_type\", must be one of #{validator.allowable_values}."
      end
      @payment_link_type = payment_link_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          merchant_id == o.merchant_id &&
          title == o.title &&
          payment_link == o.payment_link &&
          short_link == o.short_link &&
          amount == o.amount &&
          payment_description == o.payment_description &&
          expire_in == o.expire_in &&
          expire_in_unit == o.expire_in_unit &&
          expire_on == o.expire_on &&
          payments == o.payments &&
          no_of_payment_made == o.no_of_payment_made &&
          total_paid_amount == o.total_paid_amount &&
          link_status == o.link_status &&
          invoice_number == o.invoice_number &&
          created_on == o.created_on &&
          created_by == o.created_by &&
          modified_on == o.modified_on &&
          modified_by == o.modified_by &&
          short_description == o.short_description &&
          response_type == o.response_type &&
          callback_parameters == o.callback_parameters &&
          customers == o.customers &&
          line_items == o.line_items &&
          display_settings == o.display_settings &&
          splits == o.splits &&
          save_for_future == o.save_for_future &&
          quote_key == o.quote_key &&
          account_number == o.account_number &&
          reference_type == o.reference_type &&
          reference_number == o.reference_number &&
          reference_key == o.reference_key &&
          reference_data_list == o.reference_data_list &&
          enable_premium_finance == o.enable_premium_finance &&
          is_premium_financier == o.is_premium_financier &&
          pfr == o.pfr &&
          payment_link_type == o.payment_link_type &&
          suppress_technology_fee == o.suppress_technology_fee &&
          override_technology_fee == o.override_technology_fee &&
          is_pf_lite == o.is_pf_lite &&
          is_pay_in_full == o.is_pay_in_full
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, merchant_id, title, payment_link, short_link, amount, payment_description, expire_in, expire_in_unit, expire_on, payments, no_of_payment_made, total_paid_amount, link_status, invoice_number, created_on, created_by, modified_on, modified_by, short_description, response_type, callback_parameters, customers, line_items, display_settings, splits, save_for_future, quote_key, account_number, reference_type, reference_number, reference_key, reference_data_list, enable_premium_finance, is_premium_financier, pfr, payment_link_type, suppress_technology_fee, override_technology_fee, is_pf_lite, is_pay_in_full].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
