=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PaymentIntentRequest
    attr_accessor :title

    attr_accessor :amount

    attr_accessor :invoice_number

    attr_accessor :expires_in

    attr_accessor :short_description

    attr_accessor :payment_description

    attr_accessor :merchant_token

    attr_accessor :intent

    attr_accessor :save_for_future

    attr_accessor :enable_premium_finance

    attr_accessor :splits

    attr_accessor :quote_key

    attr_accessor :account_number

    attr_accessor :suppress_technology_fee

    attr_accessor :override_technology_fee

    attr_accessor :is_premium_financier

    attr_accessor :pfr

    attr_accessor :save_customer

    attr_accessor :customers

    attr_accessor :additional_details_preference

    attr_accessor :selected_customer_fields

    attr_accessor :reference_type

    attr_accessor :reference_number

    attr_accessor :reference_key

    attr_accessor :reference_data_list

    attr_accessor :display_mode

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'title' => :'title',
        :'amount' => :'amount',
        :'invoice_number' => :'invoiceNumber',
        :'expires_in' => :'expiresIn',
        :'short_description' => :'shortDescription',
        :'payment_description' => :'paymentDescription',
        :'merchant_token' => :'merchantToken',
        :'intent' => :'intent',
        :'save_for_future' => :'saveForFuture',
        :'enable_premium_finance' => :'enablePremiumFinance',
        :'splits' => :'splits',
        :'quote_key' => :'quoteKey',
        :'account_number' => :'accountNumber',
        :'suppress_technology_fee' => :'suppressTechnologyFee',
        :'override_technology_fee' => :'overrideTechnologyFee',
        :'is_premium_financier' => :'isPremiumFinancier',
        :'pfr' => :'pfr',
        :'save_customer' => :'saveCustomer',
        :'customers' => :'customers',
        :'additional_details_preference' => :'additionalDetailsPreference',
        :'selected_customer_fields' => :'selectedCustomerFields',
        :'reference_type' => :'referenceType',
        :'reference_number' => :'referenceNumber',
        :'reference_key' => :'referenceKey',
        :'reference_data_list' => :'referenceDataList',
        :'display_mode' => :'displayMode'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'title' => :'String',
        :'amount' => :'Float',
        :'invoice_number' => :'String',
        :'expires_in' => :'String',
        :'short_description' => :'String',
        :'payment_description' => :'String',
        :'merchant_token' => :'String',
        :'intent' => :'PaymentIntentRequestIntent',
        :'save_for_future' => :'Boolean',
        :'enable_premium_finance' => :'Boolean',
        :'splits' => :'Array<PaymentIntentRequestSplitsInner>',
        :'quote_key' => :'String',
        :'account_number' => :'String',
        :'suppress_technology_fee' => :'Boolean',
        :'override_technology_fee' => :'Float',
        :'is_premium_financier' => :'Boolean',
        :'pfr' => :'PaymentIntentRequestPfr',
        :'save_customer' => :'Boolean',
        :'customers' => :'Array<PaymentIntentRequestCustomersInner>',
        :'additional_details_preference' => :'String',
        :'selected_customer_fields' => :'String',
        :'reference_type' => :'String',
        :'reference_number' => :'String',
        :'reference_key' => :'String',
        :'reference_data_list' => :'Array<PaymentIntentRequestReferenceDataListInner>',
        :'display_mode' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PaymentIntentRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PaymentIntentRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'invoice_number')
        self.invoice_number = attributes[:'invoice_number']
      end

      if attributes.key?(:'expires_in')
        self.expires_in = attributes[:'expires_in']
      end

      if attributes.key?(:'short_description')
        self.short_description = attributes[:'short_description']
      end

      if attributes.key?(:'payment_description')
        self.payment_description = attributes[:'payment_description']
      end

      if attributes.key?(:'merchant_token')
        self.merchant_token = attributes[:'merchant_token']
      end

      if attributes.key?(:'intent')
        self.intent = attributes[:'intent']
      else
        self.intent = nil
      end

      if attributes.key?(:'save_for_future')
        self.save_for_future = attributes[:'save_for_future']
      end

      if attributes.key?(:'enable_premium_finance')
        self.enable_premium_finance = attributes[:'enable_premium_finance']
      end

      if attributes.key?(:'splits')
        if (value = attributes[:'splits']).is_a?(Array)
          self.splits = value
        end
      end

      if attributes.key?(:'quote_key')
        self.quote_key = attributes[:'quote_key']
      end

      if attributes.key?(:'account_number')
        self.account_number = attributes[:'account_number']
      end

      if attributes.key?(:'suppress_technology_fee')
        self.suppress_technology_fee = attributes[:'suppress_technology_fee']
      end

      if attributes.key?(:'override_technology_fee')
        self.override_technology_fee = attributes[:'override_technology_fee']
      end

      if attributes.key?(:'is_premium_financier')
        self.is_premium_financier = attributes[:'is_premium_financier']
      end

      if attributes.key?(:'pfr')
        self.pfr = attributes[:'pfr']
      end

      if attributes.key?(:'save_customer')
        self.save_customer = attributes[:'save_customer']
      end

      if attributes.key?(:'customers')
        if (value = attributes[:'customers']).is_a?(Array)
          self.customers = value
        end
      end

      if attributes.key?(:'additional_details_preference')
        self.additional_details_preference = attributes[:'additional_details_preference']
      else
        self.additional_details_preference = nil
      end

      if attributes.key?(:'selected_customer_fields')
        self.selected_customer_fields = attributes[:'selected_customer_fields']
      end

      if attributes.key?(:'reference_type')
        self.reference_type = attributes[:'reference_type']
      end

      if attributes.key?(:'reference_number')
        self.reference_number = attributes[:'reference_number']
      end

      if attributes.key?(:'reference_key')
        self.reference_key = attributes[:'reference_key']
      end

      if attributes.key?(:'reference_data_list')
        if (value = attributes[:'reference_data_list']).is_a?(Array)
          self.reference_data_list = value
        end
      end

      if attributes.key?(:'display_mode')
        self.display_mode = attributes[:'display_mode']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @intent.nil?
        invalid_properties.push('invalid value for "intent", intent cannot be nil.')
      end

      if @additional_details_preference.nil?
        invalid_properties.push('invalid value for "additional_details_preference", additional_details_preference cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @title.nil?
      return false if @amount.nil?
      return false if @intent.nil?
      return false if @additional_details_preference.nil?
      additional_details_preference_validator = EnumAttributeValidator.new('String', ["None", "AskShopper", "ManualEnter", "NoAdditionalDetails", "ManualEnterEditNotAllowed"])
      return false unless additional_details_preference_validator.valid?(@additional_details_preference)
      reference_type_validator = EnumAttributeValidator.new('String', ["None", "QuoteId", "AccountNumber", "PolicyNumber", "InvoiceNumber", "Other"])
      return false unless reference_type_validator.valid?(@reference_type)
      display_mode_validator = EnumAttributeValidator.new('String', ["None", "PremiumFinanceOnly", "Both"])
      return false unless display_mode_validator.valid?(@display_mode)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] additional_details_preference Object to be assigned
    def additional_details_preference=(additional_details_preference)
      validator = EnumAttributeValidator.new('String', ["None", "AskShopper", "ManualEnter", "NoAdditionalDetails", "ManualEnterEditNotAllowed"])
      unless validator.valid?(additional_details_preference)
        fail ArgumentError, "invalid value for \"additional_details_preference\", must be one of #{validator.allowable_values}."
      end
      @additional_details_preference = additional_details_preference
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] reference_type Object to be assigned
    def reference_type=(reference_type)
      validator = EnumAttributeValidator.new('String', ["None", "QuoteId", "AccountNumber", "PolicyNumber", "InvoiceNumber", "Other"])
      unless validator.valid?(reference_type)
        fail ArgumentError, "invalid value for \"reference_type\", must be one of #{validator.allowable_values}."
      end
      @reference_type = reference_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] display_mode Object to be assigned
    def display_mode=(display_mode)
      validator = EnumAttributeValidator.new('String', ["None", "PremiumFinanceOnly", "Both"])
      unless validator.valid?(display_mode)
        fail ArgumentError, "invalid value for \"display_mode\", must be one of #{validator.allowable_values}."
      end
      @display_mode = display_mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          title == o.title &&
          amount == o.amount &&
          invoice_number == o.invoice_number &&
          expires_in == o.expires_in &&
          short_description == o.short_description &&
          payment_description == o.payment_description &&
          merchant_token == o.merchant_token &&
          intent == o.intent &&
          save_for_future == o.save_for_future &&
          enable_premium_finance == o.enable_premium_finance &&
          splits == o.splits &&
          quote_key == o.quote_key &&
          account_number == o.account_number &&
          suppress_technology_fee == o.suppress_technology_fee &&
          override_technology_fee == o.override_technology_fee &&
          is_premium_financier == o.is_premium_financier &&
          pfr == o.pfr &&
          save_customer == o.save_customer &&
          customers == o.customers &&
          additional_details_preference == o.additional_details_preference &&
          selected_customer_fields == o.selected_customer_fields &&
          reference_type == o.reference_type &&
          reference_number == o.reference_number &&
          reference_key == o.reference_key &&
          reference_data_list == o.reference_data_list &&
          display_mode == o.display_mode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [title, amount, invoice_number, expires_in, short_description, payment_description, merchant_token, intent, save_for_future, enable_premium_finance, splits, quote_key, account_number, suppress_technology_fee, override_technology_fee, is_premium_financier, pfr, save_customer, customers, additional_details_preference, selected_customer_fields, reference_type, reference_number, reference_key, reference_data_list, display_mode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
