=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PaymentRequest
    attr_accessor :token

    attr_accessor :type

    attr_accessor :transaction_code

    attr_accessor :billing_contact

    attr_accessor :phone_country_code

    attr_accessor :channel_type

    attr_accessor :process_method

    attr_accessor :tender_info

    attr_accessor :invoice_no

    attr_accessor :reference_no

    attr_accessor :payment_reference

    attr_accessor :remarks

    attr_accessor :save_customer

    attr_accessor :captcha_token

    attr_accessor :action_name

    attr_accessor :additional_fields

    attr_accessor :issuer

    attr_accessor :splits

    attr_accessor :operation_type

    attr_accessor :suppress_technology_fee

    attr_accessor :override_technology_fee

    attr_accessor :is_premium_financier

    attr_accessor :pfr

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'token' => :'token',
        :'type' => :'type',
        :'transaction_code' => :'transactionCode',
        :'billing_contact' => :'billingContact',
        :'phone_country_code' => :'phoneCountryCode',
        :'channel_type' => :'channelType',
        :'process_method' => :'processMethod',
        :'tender_info' => :'tenderInfo',
        :'invoice_no' => :'invoiceNo',
        :'reference_no' => :'referenceNo',
        :'payment_reference' => :'paymentReference',
        :'remarks' => :'remarks',
        :'save_customer' => :'saveCustomer',
        :'captcha_token' => :'captchaToken',
        :'action_name' => :'actionName',
        :'additional_fields' => :'additionalFields',
        :'issuer' => :'issuer',
        :'splits' => :'splits',
        :'operation_type' => :'operationType',
        :'suppress_technology_fee' => :'suppressTechnologyFee',
        :'override_technology_fee' => :'overrideTechnologyFee',
        :'is_premium_financier' => :'isPremiumFinancier',
        :'pfr' => :'pfr'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'token' => :'String',
        :'type' => :'String',
        :'transaction_code' => :'String',
        :'billing_contact' => :'TransactionPaymentResponseBillingContact',
        :'phone_country_code' => :'String',
        :'channel_type' => :'String',
        :'process_method' => :'String',
        :'tender_info' => :'PaymentRequestTenderInfo',
        :'invoice_no' => :'String',
        :'reference_no' => :'String',
        :'payment_reference' => :'String',
        :'remarks' => :'String',
        :'save_customer' => :'Boolean',
        :'captcha_token' => :'String',
        :'action_name' => :'String',
        :'additional_fields' => :'Hash<String, String>',
        :'issuer' => :'String',
        :'splits' => :'Array<PaymentIntentRequestSplitsInner>',
        :'operation_type' => :'String',
        :'suppress_technology_fee' => :'Boolean',
        :'override_technology_fee' => :'Float',
        :'is_premium_financier' => :'Boolean',
        :'pfr' => :'PaymentIntentRequestPfr'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PaymentRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PaymentRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'token')
        self.token = attributes[:'token']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'transaction_code')
        self.transaction_code = attributes[:'transaction_code']
      else
        self.transaction_code = nil
      end

      if attributes.key?(:'billing_contact')
        self.billing_contact = attributes[:'billing_contact']
      end

      if attributes.key?(:'phone_country_code')
        self.phone_country_code = attributes[:'phone_country_code']
      end

      if attributes.key?(:'channel_type')
        self.channel_type = attributes[:'channel_type']
      else
        self.channel_type = nil
      end

      if attributes.key?(:'process_method')
        self.process_method = attributes[:'process_method']
      end

      if attributes.key?(:'tender_info')
        self.tender_info = attributes[:'tender_info']
      else
        self.tender_info = nil
      end

      if attributes.key?(:'invoice_no')
        self.invoice_no = attributes[:'invoice_no']
      end

      if attributes.key?(:'reference_no')
        self.reference_no = attributes[:'reference_no']
      end

      if attributes.key?(:'payment_reference')
        self.payment_reference = attributes[:'payment_reference']
      end

      if attributes.key?(:'remarks')
        self.remarks = attributes[:'remarks']
      end

      if attributes.key?(:'save_customer')
        self.save_customer = attributes[:'save_customer']
      end

      if attributes.key?(:'captcha_token')
        self.captcha_token = attributes[:'captcha_token']
      end

      if attributes.key?(:'action_name')
        self.action_name = attributes[:'action_name']
      end

      if attributes.key?(:'additional_fields')
        if (value = attributes[:'additional_fields']).is_a?(Hash)
          self.additional_fields = value
        end
      end

      if attributes.key?(:'issuer')
        self.issuer = attributes[:'issuer']
      end

      if attributes.key?(:'splits')
        if (value = attributes[:'splits']).is_a?(Array)
          self.splits = value
        end
      end

      if attributes.key?(:'operation_type')
        self.operation_type = attributes[:'operation_type']
      end

      if attributes.key?(:'suppress_technology_fee')
        self.suppress_technology_fee = attributes[:'suppress_technology_fee']
      end

      if attributes.key?(:'override_technology_fee')
        self.override_technology_fee = attributes[:'override_technology_fee']
      end

      if attributes.key?(:'is_premium_financier')
        self.is_premium_financier = attributes[:'is_premium_financier']
      end

      if attributes.key?(:'pfr')
        self.pfr = attributes[:'pfr']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @transaction_code.nil?
        invalid_properties.push('invalid value for "transaction_code", transaction_code cannot be nil.')
      end

      if @channel_type.nil?
        invalid_properties.push('invalid value for "channel_type", channel_type cannot be nil.')
      end

      if @tender_info.nil?
        invalid_properties.push('invalid value for "tender_info", tender_info cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["AnytimePayment", "SubDomain", "PaymentIntent", "PaymentLink", "OpenPayment", "TokenLink"])
      return false unless type_validator.valid?(@type)
      return false if @transaction_code.nil?
      return false if @channel_type.nil?
      channel_type_validator = EnumAttributeValidator.new('String', ["CreditCard", "DebitCard", "ACH"])
      return false unless channel_type_validator.valid?(@channel_type)
      process_method_validator = EnumAttributeValidator.new('String', ["NotDefined", "ACH", "CardNotPresent"])
      return false unless process_method_validator.valid?(@process_method)
      return false if @tender_info.nil?
      operation_type_validator = EnumAttributeValidator.new('String', ["Sale", "VerifyOnly", "ForceSale", "Adjust", "Activate", "Deactivate", "Reload", "Refund", "Inquire", "ReverseAuth"])
      return false unless operation_type_validator.valid?(@operation_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["AnytimePayment", "SubDomain", "PaymentIntent", "PaymentLink", "OpenPayment", "TokenLink"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] channel_type Object to be assigned
    def channel_type=(channel_type)
      validator = EnumAttributeValidator.new('String', ["CreditCard", "DebitCard", "ACH"])
      unless validator.valid?(channel_type)
        fail ArgumentError, "invalid value for \"channel_type\", must be one of #{validator.allowable_values}."
      end
      @channel_type = channel_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] process_method Object to be assigned
    def process_method=(process_method)
      validator = EnumAttributeValidator.new('String', ["NotDefined", "ACH", "CardNotPresent"])
      unless validator.valid?(process_method)
        fail ArgumentError, "invalid value for \"process_method\", must be one of #{validator.allowable_values}."
      end
      @process_method = process_method
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] operation_type Object to be assigned
    def operation_type=(operation_type)
      validator = EnumAttributeValidator.new('String', ["Sale", "VerifyOnly", "ForceSale", "Adjust", "Activate", "Deactivate", "Reload", "Refund", "Inquire", "ReverseAuth"])
      unless validator.valid?(operation_type)
        fail ArgumentError, "invalid value for \"operation_type\", must be one of #{validator.allowable_values}."
      end
      @operation_type = operation_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          token == o.token &&
          type == o.type &&
          transaction_code == o.transaction_code &&
          billing_contact == o.billing_contact &&
          phone_country_code == o.phone_country_code &&
          channel_type == o.channel_type &&
          process_method == o.process_method &&
          tender_info == o.tender_info &&
          invoice_no == o.invoice_no &&
          reference_no == o.reference_no &&
          payment_reference == o.payment_reference &&
          remarks == o.remarks &&
          save_customer == o.save_customer &&
          captcha_token == o.captcha_token &&
          action_name == o.action_name &&
          additional_fields == o.additional_fields &&
          issuer == o.issuer &&
          splits == o.splits &&
          operation_type == o.operation_type &&
          suppress_technology_fee == o.suppress_technology_fee &&
          override_technology_fee == o.override_technology_fee &&
          is_premium_financier == o.is_premium_financier &&
          pfr == o.pfr
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [token, type, transaction_code, billing_contact, phone_country_code, channel_type, process_method, tender_info, invoice_no, reference_no, payment_reference, remarks, save_customer, captcha_token, action_name, additional_fields, issuer, splits, operation_type, suppress_technology_fee, override_technology_fee, is_premium_financier, pfr].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
