=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PFEndorsementRequestQuotePoliciesInner
    # This denotes the policy identifier.
    attr_accessor :policy_id

    # This denotes the premium amount.
    attr_accessor :premium

    # This denotes the down amount.
    attr_accessor :down

    # This denotes the down percentage.
    attr_accessor :down_percent

    # This denotes the fee amount.
    attr_accessor :fee

    # This denotes the tax amount.
    attr_accessor :tax

    # This denotes the policy number.
    attr_accessor :policy_number

    attr_accessor :company

    attr_accessor :ga

    attr_accessor :broker

    # This denotes the coverage and it is required if adding new policy.
    attr_accessor :coverage

    # This denotes the effective date.
    attr_accessor :effective_date

    # This denotes the expiration date and it is required if adding new policy.
    attr_accessor :expiration_date

    # This denotes the number of terms.
    attr_accessor :term

    # This denotes the minimum earned amount.
    attr_accessor :minimum_earned

    # This denotes the minimum earned percent.
    attr_accessor :minimum_earned_percent

    # This denotes the flag if it is auditable or not.
    attr_accessor :auditable

    # This denotes the cancel days.
    attr_accessor :cancel_days

    # This denotes the flag of loss payee requested.
    attr_accessor :loss_payee_requested

    # This denotes the minimum liability.
    attr_accessor :minimum_liability

    # This denotes the maximum liability.
    attr_accessor :maximum_liability

    attr_accessor :total_pay_funding

    attr_accessor :policy_fee

    # This denotes the invoice number.
    attr_accessor :invoice_number

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'policy_id' => :'policyId',
        :'premium' => :'premium',
        :'down' => :'down',
        :'down_percent' => :'downPercent',
        :'fee' => :'fee',
        :'tax' => :'tax',
        :'policy_number' => :'policyNumber',
        :'company' => :'company',
        :'ga' => :'ga',
        :'broker' => :'broker',
        :'coverage' => :'coverage',
        :'effective_date' => :'effectiveDate',
        :'expiration_date' => :'expirationDate',
        :'term' => :'term',
        :'minimum_earned' => :'minimumEarned',
        :'minimum_earned_percent' => :'minimumEarnedPercent',
        :'auditable' => :'auditable',
        :'cancel_days' => :'cancelDays',
        :'loss_payee_requested' => :'lossPayeeRequested',
        :'minimum_liability' => :'minimumLiability',
        :'maximum_liability' => :'maximumLiability',
        :'total_pay_funding' => :'totalPayFunding',
        :'policy_fee' => :'policyFee',
        :'invoice_number' => :'invoiceNumber'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'policy_id' => :'Integer',
        :'premium' => :'Float',
        :'down' => :'Float',
        :'down_percent' => :'Float',
        :'fee' => :'Float',
        :'tax' => :'Float',
        :'policy_number' => :'String',
        :'company' => :'PFEndorsementRequestQuotePoliciesInnerCompany',
        :'ga' => :'PFEndorsementRequestQuotePoliciesInnerGa',
        :'broker' => :'PFEndorsementRequestQuotePoliciesInnerGa',
        :'coverage' => :'String',
        :'effective_date' => :'String',
        :'expiration_date' => :'String',
        :'term' => :'Integer',
        :'minimum_earned' => :'Float',
        :'minimum_earned_percent' => :'Float',
        :'auditable' => :'Boolean',
        :'cancel_days' => :'String',
        :'loss_payee_requested' => :'Boolean',
        :'minimum_liability' => :'Float',
        :'maximum_liability' => :'Float',
        :'total_pay_funding' => :'Array<PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner>',
        :'policy_fee' => :'Array<PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner>',
        :'invoice_number' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PFEndorsementRequestQuotePoliciesInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PFEndorsementRequestQuotePoliciesInner`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'policy_id')
        self.policy_id = attributes[:'policy_id']
      end

      if attributes.key?(:'premium')
        self.premium = attributes[:'premium']
      else
        self.premium = nil
      end

      if attributes.key?(:'down')
        self.down = attributes[:'down']
      end

      if attributes.key?(:'down_percent')
        self.down_percent = attributes[:'down_percent']
      end

      if attributes.key?(:'fee')
        self.fee = attributes[:'fee']
      end

      if attributes.key?(:'tax')
        self.tax = attributes[:'tax']
      end

      if attributes.key?(:'policy_number')
        self.policy_number = attributes[:'policy_number']
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.key?(:'ga')
        self.ga = attributes[:'ga']
      end

      if attributes.key?(:'broker')
        self.broker = attributes[:'broker']
      end

      if attributes.key?(:'coverage')
        self.coverage = attributes[:'coverage']
      end

      if attributes.key?(:'effective_date')
        self.effective_date = attributes[:'effective_date']
      else
        self.effective_date = nil
      end

      if attributes.key?(:'expiration_date')
        self.expiration_date = attributes[:'expiration_date']
      else
        self.expiration_date = nil
      end

      if attributes.key?(:'term')
        self.term = attributes[:'term']
      end

      if attributes.key?(:'minimum_earned')
        self.minimum_earned = attributes[:'minimum_earned']
      end

      if attributes.key?(:'minimum_earned_percent')
        self.minimum_earned_percent = attributes[:'minimum_earned_percent']
      end

      if attributes.key?(:'auditable')
        self.auditable = attributes[:'auditable']
      end

      if attributes.key?(:'cancel_days')
        self.cancel_days = attributes[:'cancel_days']
      end

      if attributes.key?(:'loss_payee_requested')
        self.loss_payee_requested = attributes[:'loss_payee_requested']
      end

      if attributes.key?(:'minimum_liability')
        self.minimum_liability = attributes[:'minimum_liability']
      end

      if attributes.key?(:'maximum_liability')
        self.maximum_liability = attributes[:'maximum_liability']
      end

      if attributes.key?(:'total_pay_funding')
        if (value = attributes[:'total_pay_funding']).is_a?(Array)
          self.total_pay_funding = value
        end
      end

      if attributes.key?(:'policy_fee')
        if (value = attributes[:'policy_fee']).is_a?(Array)
          self.policy_fee = value
        end
      end

      if attributes.key?(:'invoice_number')
        self.invoice_number = attributes[:'invoice_number']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @premium.nil?
        invalid_properties.push('invalid value for "premium", premium cannot be nil.')
      end

      if @effective_date.nil?
        invalid_properties.push('invalid value for "effective_date", effective_date cannot be nil.')
      end

      if @expiration_date.nil?
        invalid_properties.push('invalid value for "expiration_date", expiration_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @premium.nil?
      return false if @effective_date.nil?
      return false if @expiration_date.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          policy_id == o.policy_id &&
          premium == o.premium &&
          down == o.down &&
          down_percent == o.down_percent &&
          fee == o.fee &&
          tax == o.tax &&
          policy_number == o.policy_number &&
          company == o.company &&
          ga == o.ga &&
          broker == o.broker &&
          coverage == o.coverage &&
          effective_date == o.effective_date &&
          expiration_date == o.expiration_date &&
          term == o.term &&
          minimum_earned == o.minimum_earned &&
          minimum_earned_percent == o.minimum_earned_percent &&
          auditable == o.auditable &&
          cancel_days == o.cancel_days &&
          loss_payee_requested == o.loss_payee_requested &&
          minimum_liability == o.minimum_liability &&
          maximum_liability == o.maximum_liability &&
          total_pay_funding == o.total_pay_funding &&
          policy_fee == o.policy_fee &&
          invoice_number == o.invoice_number
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [policy_id, premium, down, down_percent, fee, tax, policy_number, company, ga, broker, coverage, effective_date, expiration_date, term, minimum_earned, minimum_earned_percent, auditable, cancel_days, loss_payee_requested, minimum_liability, maximum_liability, total_pay_funding, policy_fee, invoice_number].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
