=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PFLitePaymentLinkRequest
    attr_accessor :quote_key

    attr_accessor :is_pay_in_full

    attr_accessor :title

    attr_accessor :payment_description

    attr_accessor :expire_in

    attr_accessor :expire_in_unit

    attr_accessor :reference_data_list

    attr_accessor :callback_parameters

    attr_accessor :customers

    attr_accessor :settings

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'quote_key' => :'quoteKey',
        :'is_pay_in_full' => :'isPayInFull',
        :'title' => :'title',
        :'payment_description' => :'paymentDescription',
        :'expire_in' => :'expireIn',
        :'expire_in_unit' => :'expireInUnit',
        :'reference_data_list' => :'referenceDataList',
        :'callback_parameters' => :'callbackParameters',
        :'customers' => :'customers',
        :'settings' => :'settings'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'quote_key' => :'String',
        :'is_pay_in_full' => :'Boolean',
        :'title' => :'String',
        :'payment_description' => :'String',
        :'expire_in' => :'String',
        :'expire_in_unit' => :'String',
        :'reference_data_list' => :'Array<PFLitePaymentLinkRequestReferenceDataListInner>',
        :'callback_parameters' => :'PFLitePaymentLinkRequestCallbackParameters',
        :'customers' => :'Array<PFLitePaymentLinkRequestCustomersInner>',
        :'settings' => :'PFLitePaymentLinkRequestSettings'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PFLitePaymentLinkRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PFLitePaymentLinkRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'quote_key')
        self.quote_key = attributes[:'quote_key']
      else
        self.quote_key = nil
      end

      if attributes.key?(:'is_pay_in_full')
        self.is_pay_in_full = attributes[:'is_pay_in_full']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'payment_description')
        self.payment_description = attributes[:'payment_description']
      else
        self.payment_description = nil
      end

      if attributes.key?(:'expire_in')
        self.expire_in = attributes[:'expire_in']
      else
        self.expire_in = nil
      end

      if attributes.key?(:'expire_in_unit')
        self.expire_in_unit = attributes[:'expire_in_unit']
      else
        self.expire_in_unit = nil
      end

      if attributes.key?(:'reference_data_list')
        if (value = attributes[:'reference_data_list']).is_a?(Array)
          self.reference_data_list = value
        end
      else
        self.reference_data_list = nil
      end

      if attributes.key?(:'callback_parameters')
        self.callback_parameters = attributes[:'callback_parameters']
      end

      if attributes.key?(:'customers')
        if (value = attributes[:'customers']).is_a?(Array)
          self.customers = value
        end
      end

      if attributes.key?(:'settings')
        self.settings = attributes[:'settings']
      else
        self.settings = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @quote_key.nil?
        invalid_properties.push('invalid value for "quote_key", quote_key cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @payment_description.nil?
        invalid_properties.push('invalid value for "payment_description", payment_description cannot be nil.')
      end

      if @expire_in.nil?
        invalid_properties.push('invalid value for "expire_in", expire_in cannot be nil.')
      end

      if @expire_in_unit.nil?
        invalid_properties.push('invalid value for "expire_in_unit", expire_in_unit cannot be nil.')
      end

      if @reference_data_list.nil?
        invalid_properties.push('invalid value for "reference_data_list", reference_data_list cannot be nil.')
      end

      if @settings.nil?
        invalid_properties.push('invalid value for "settings", settings cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @quote_key.nil?
      return false if @title.nil?
      return false if @payment_description.nil?
      return false if @expire_in.nil?
      return false if @expire_in_unit.nil?
      expire_in_unit_validator = EnumAttributeValidator.new('String', ["NA", "Seconds", "Minutes", "Hours", "Days", "Weeks"])
      return false unless expire_in_unit_validator.valid?(@expire_in_unit)
      return false if @reference_data_list.nil?
      return false if @settings.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] expire_in_unit Object to be assigned
    def expire_in_unit=(expire_in_unit)
      validator = EnumAttributeValidator.new('String', ["NA", "Seconds", "Minutes", "Hours", "Days", "Weeks"])
      unless validator.valid?(expire_in_unit)
        fail ArgumentError, "invalid value for \"expire_in_unit\", must be one of #{validator.allowable_values}."
      end
      @expire_in_unit = expire_in_unit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          quote_key == o.quote_key &&
          is_pay_in_full == o.is_pay_in_full &&
          title == o.title &&
          payment_description == o.payment_description &&
          expire_in == o.expire_in &&
          expire_in_unit == o.expire_in_unit &&
          reference_data_list == o.reference_data_list &&
          callback_parameters == o.callback_parameters &&
          customers == o.customers &&
          settings == o.settings
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [quote_key, is_pay_in_full, title, payment_description, expire_in, expire_in_unit, reference_data_list, callback_parameters, customers, settings].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
