=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class QuoteRequestInsured
    attr_accessor :agent_customer_number

    attr_accessor :email

    attr_accessor :care_of

    attr_accessor :unique_id

    attr_accessor :address

    attr_accessor :has_data_change_agent_customer_number

    attr_accessor :has_data_change_name

    attr_accessor :has_data_change_address1

    attr_accessor :has_data_change_address2

    attr_accessor :has_data_change_city

    attr_accessor :has_data_change_state

    attr_accessor :has_data_change_zip

    attr_accessor :has_data_change_phone

    attr_accessor :has_data_change_email

    attr_accessor :has_data_change_care_of

    attr_accessor :has_data_change_insured

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'agent_customer_number' => :'agentCustomerNumber',
        :'email' => :'email',
        :'care_of' => :'careOf',
        :'unique_id' => :'uniqueId',
        :'address' => :'address',
        :'has_data_change_agent_customer_number' => :'hasDataChangeAgentCustomerNumber',
        :'has_data_change_name' => :'hasDataChangeName',
        :'has_data_change_address1' => :'hasDataChangeAddress1',
        :'has_data_change_address2' => :'hasDataChangeAddress2',
        :'has_data_change_city' => :'hasDataChangeCity',
        :'has_data_change_state' => :'hasDataChangeState',
        :'has_data_change_zip' => :'hasDataChangeZip',
        :'has_data_change_phone' => :'hasDataChangePhone',
        :'has_data_change_email' => :'hasDataChangeEmail',
        :'has_data_change_care_of' => :'hasDataChangeCareOf',
        :'has_data_change_insured' => :'hasDataChangeInsured'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'agent_customer_number' => :'String',
        :'email' => :'String',
        :'care_of' => :'String',
        :'unique_id' => :'String',
        :'address' => :'QuoteRequestInsuredAddress',
        :'has_data_change_agent_customer_number' => :'Boolean',
        :'has_data_change_name' => :'Boolean',
        :'has_data_change_address1' => :'Boolean',
        :'has_data_change_address2' => :'Boolean',
        :'has_data_change_city' => :'Boolean',
        :'has_data_change_state' => :'Boolean',
        :'has_data_change_zip' => :'Boolean',
        :'has_data_change_phone' => :'Boolean',
        :'has_data_change_email' => :'Boolean',
        :'has_data_change_care_of' => :'Boolean',
        :'has_data_change_insured' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::QuoteRequestInsured` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::QuoteRequestInsured`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'agent_customer_number')
        self.agent_customer_number = attributes[:'agent_customer_number']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'care_of')
        self.care_of = attributes[:'care_of']
      end

      if attributes.key?(:'unique_id')
        self.unique_id = attributes[:'unique_id']
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      else
        self.address = nil
      end

      if attributes.key?(:'has_data_change_agent_customer_number')
        self.has_data_change_agent_customer_number = attributes[:'has_data_change_agent_customer_number']
      end

      if attributes.key?(:'has_data_change_name')
        self.has_data_change_name = attributes[:'has_data_change_name']
      end

      if attributes.key?(:'has_data_change_address1')
        self.has_data_change_address1 = attributes[:'has_data_change_address1']
      end

      if attributes.key?(:'has_data_change_address2')
        self.has_data_change_address2 = attributes[:'has_data_change_address2']
      end

      if attributes.key?(:'has_data_change_city')
        self.has_data_change_city = attributes[:'has_data_change_city']
      end

      if attributes.key?(:'has_data_change_state')
        self.has_data_change_state = attributes[:'has_data_change_state']
      end

      if attributes.key?(:'has_data_change_zip')
        self.has_data_change_zip = attributes[:'has_data_change_zip']
      end

      if attributes.key?(:'has_data_change_phone')
        self.has_data_change_phone = attributes[:'has_data_change_phone']
      end

      if attributes.key?(:'has_data_change_email')
        self.has_data_change_email = attributes[:'has_data_change_email']
      end

      if attributes.key?(:'has_data_change_care_of')
        self.has_data_change_care_of = attributes[:'has_data_change_care_of']
      end

      if attributes.key?(:'has_data_change_insured')
        self.has_data_change_insured = attributes[:'has_data_change_insured']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @address.nil?
        invalid_properties.push('invalid value for "address", address cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @email.nil?
      return false if @address.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          agent_customer_number == o.agent_customer_number &&
          email == o.email &&
          care_of == o.care_of &&
          unique_id == o.unique_id &&
          address == o.address &&
          has_data_change_agent_customer_number == o.has_data_change_agent_customer_number &&
          has_data_change_name == o.has_data_change_name &&
          has_data_change_address1 == o.has_data_change_address1 &&
          has_data_change_address2 == o.has_data_change_address2 &&
          has_data_change_city == o.has_data_change_city &&
          has_data_change_state == o.has_data_change_state &&
          has_data_change_zip == o.has_data_change_zip &&
          has_data_change_phone == o.has_data_change_phone &&
          has_data_change_email == o.has_data_change_email &&
          has_data_change_care_of == o.has_data_change_care_of &&
          has_data_change_insured == o.has_data_change_insured
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [agent_customer_number, email, care_of, unique_id, address, has_data_change_agent_customer_number, has_data_change_name, has_data_change_address1, has_data_change_address2, has_data_change_city, has_data_change_state, has_data_change_zip, has_data_change_phone, has_data_change_email, has_data_change_care_of, has_data_change_insured].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
