=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class VerifyBankAccountResponse
    attr_accessor :id

    attr_accessor :verification_entity_id

    attr_accessor :verifying_entity

    attr_accessor :verification_status

    attr_accessor :status_reason

    attr_accessor :estimated_verification_date

    attr_accessor :event_id

    attr_accessor :event_type

    attr_accessor :bank_account_entity_id

    attr_accessor :bank_account_entity_type

    attr_accessor :created_on

    attr_accessor :created_by

    attr_accessor :modified_on

    attr_accessor :modified_by

    attr_accessor :http_response

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'verification_entity_id' => :'verificationEntityId',
        :'verifying_entity' => :'verifyingEntity',
        :'verification_status' => :'verificationStatus',
        :'status_reason' => :'statusReason',
        :'estimated_verification_date' => :'estimatedVerificationDate',
        :'event_id' => :'eventId',
        :'event_type' => :'eventType',
        :'bank_account_entity_id' => :'bankAccountEntityId',
        :'bank_account_entity_type' => :'bankAccountEntityType',
        :'created_on' => :'createdOn',
        :'created_by' => :'createdBy',
        :'modified_on' => :'modifiedOn',
        :'modified_by' => :'modifiedBy',
        :'http_response' => :'httpResponse'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'verification_entity_id' => :'String',
        :'verifying_entity' => :'String',
        :'verification_status' => :'String',
        :'status_reason' => :'String',
        :'estimated_verification_date' => :'String',
        :'event_id' => :'String',
        :'event_type' => :'String',
        :'bank_account_entity_id' => :'Float',
        :'bank_account_entity_type' => :'String',
        :'created_on' => :'String',
        :'created_by' => :'String',
        :'modified_on' => :'String',
        :'modified_by' => :'String',
        :'http_response' => :'VerifyBankAccountResponseHttpResponse'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::VerifyBankAccountResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::VerifyBankAccountResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'verification_entity_id')
        self.verification_entity_id = attributes[:'verification_entity_id']
      end

      if attributes.key?(:'verifying_entity')
        self.verifying_entity = attributes[:'verifying_entity']
      end

      if attributes.key?(:'verification_status')
        self.verification_status = attributes[:'verification_status']
      end

      if attributes.key?(:'status_reason')
        self.status_reason = attributes[:'status_reason']
      end

      if attributes.key?(:'estimated_verification_date')
        self.estimated_verification_date = attributes[:'estimated_verification_date']
      end

      if attributes.key?(:'event_id')
        self.event_id = attributes[:'event_id']
      end

      if attributes.key?(:'event_type')
        self.event_type = attributes[:'event_type']
      end

      if attributes.key?(:'bank_account_entity_id')
        self.bank_account_entity_id = attributes[:'bank_account_entity_id']
      end

      if attributes.key?(:'bank_account_entity_type')
        self.bank_account_entity_type = attributes[:'bank_account_entity_type']
      end

      if attributes.key?(:'created_on')
        self.created_on = attributes[:'created_on']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'modified_on')
        self.modified_on = attributes[:'modified_on']
      end

      if attributes.key?(:'modified_by')
        self.modified_by = attributes[:'modified_by']
      end

      if attributes.key?(:'http_response')
        self.http_response = attributes[:'http_response']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      verifying_entity_validator = EnumAttributeValidator.new('String', ["Other", "Orum"])
      return false unless verifying_entity_validator.valid?(@verifying_entity)
      verification_status_validator = EnumAttributeValidator.new('String', ["Pending", "Valid", "Closed", "Invalid", "Failed"])
      return false unless verification_status_validator.valid?(@verification_status)
      bank_account_entity_type_validator = EnumAttributeValidator.new('String', ["None", "Vendor", "Merchant"])
      return false unless bank_account_entity_type_validator.valid?(@bank_account_entity_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] verifying_entity Object to be assigned
    def verifying_entity=(verifying_entity)
      validator = EnumAttributeValidator.new('String', ["Other", "Orum"])
      unless validator.valid?(verifying_entity)
        fail ArgumentError, "invalid value for \"verifying_entity\", must be one of #{validator.allowable_values}."
      end
      @verifying_entity = verifying_entity
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] verification_status Object to be assigned
    def verification_status=(verification_status)
      validator = EnumAttributeValidator.new('String', ["Pending", "Valid", "Closed", "Invalid", "Failed"])
      unless validator.valid?(verification_status)
        fail ArgumentError, "invalid value for \"verification_status\", must be one of #{validator.allowable_values}."
      end
      @verification_status = verification_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bank_account_entity_type Object to be assigned
    def bank_account_entity_type=(bank_account_entity_type)
      validator = EnumAttributeValidator.new('String', ["None", "Vendor", "Merchant"])
      unless validator.valid?(bank_account_entity_type)
        fail ArgumentError, "invalid value for \"bank_account_entity_type\", must be one of #{validator.allowable_values}."
      end
      @bank_account_entity_type = bank_account_entity_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          verification_entity_id == o.verification_entity_id &&
          verifying_entity == o.verifying_entity &&
          verification_status == o.verification_status &&
          status_reason == o.status_reason &&
          estimated_verification_date == o.estimated_verification_date &&
          event_id == o.event_id &&
          event_type == o.event_type &&
          bank_account_entity_id == o.bank_account_entity_id &&
          bank_account_entity_type == o.bank_account_entity_type &&
          created_on == o.created_on &&
          created_by == o.created_by &&
          modified_on == o.modified_on &&
          modified_by == o.modified_by &&
          http_response == o.http_response
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, verification_entity_id, verifying_entity, verification_status, status_reason, estimated_verification_date, event_id, event_type, bank_account_entity_id, bank_account_entity_type, created_on, created_by, modified_on, modified_by, http_response].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
