=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require_relative '../spec_helper'
require 'json'
require 'openapi_client'
require 'date'

# Setup authorization
OpenapiClient.configure do |config|

end

time = Time.new
title = "Ruby PL " + time.day.to_s + time.month.to_s + time.year.to_s + '-' + time.hour.to_s + '-' + time.min.to_s + '-' + time.sec.to_s
title_update = title + " UPDATED"
api_instance = OpenapiClient::SecurePaymentLinksApi.new

file = File.read('./config.json')
data_hash = JSON.parse(file)
x_api_key = data_hash['xApiKey']
x_app_key = data_hash['xAppKey']
x_version = data_hash['xVersion']
origin = data_hash['origin']

opts = OpenapiClient::PaymentLinkRequest.new(
  title: title,
  merchant_id: x_app_key,
  payment_description: "Test Premium down payment.",
  amount: "200",
  expire_in: "7",
  expire_in_unit: 4,
  reference_type: "2",
  reference_number: "TEST00000002",
  response_type: 1,
  callback_parameters: OpenapiClient::PaymentLinkRequestCallbackParameters.new(
    callback_api_url: "https://www.anddone.com",
    callback_message: "Thank you for your payment!"
  ),
  customers: [OpenapiClient::PaymentLinkResponseCustomersInner.new({
    first_name: "Testing",
    last_name: "Tester",
    email: "tt@test.com",
    phone: "9876543210",
    })],
  settings: OpenapiClient::PaymentLinkRequestSettings.new({
    additional_details_preference: 2,
    intent: OpenapiClient::PaymentLinkRequestSettingsIntent.new({
      payment_types: ["ACH", "CreditCard", "DebitCard"]
    })
  })
)
opts_updated = OpenapiClient::PaymentLinkRequest.new(
  title: title_update,
  amount: "125.75",
  expire_in: "7",
  expire_in_unit: 3
)

opts_id = OpenapiClient::SecurePaymentLinkRequest.new(
  payment_link_id: ""
)

begin
  result = api_instance.secure_paymentlinks_post(x_api_key, x_app_key, x_version, origin, opts)
  # p result
  # p result.title
  p 'Success - Create Payment Link'
  id = result.id
  result_updated = api_instance.secure_paymentlinks_id_put(x_api_key, x_app_key, x_version, origin, id, opts_updated)
  p 'Success - Update Payment Link'
  # p result_updated
  # p result_updated.title
  opts_id.payment_link_id = id
  result_get = api_instance.secure_paymentlinks_details_post(x_api_key, x_app_key, x_version, origin, opts_id)
  p 'Success - Get Payment Link Details'
  # p result.id
  result_del = api_instance.secure_paymentlinks_expirations_post(x_api_key, x_app_key, x_version, origin, opts_id)
  p 'Success - Expire Payment Link'
  # p result_del
rescue OpenapiClient::ApiError => e
  puts "Exception when calling Payment Link APIs: #{e}"
end


# Unit tests for OpenapiClient::SecurePaymentLinksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SecurePaymentLinksApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SecurePaymentLinksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecurePaymentLinksApi' do
    it 'should create an instance of SecurePaymentLinksApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SecurePaymentLinksApi)
    end
  end

  # unit tests for secure_paymentlinks_details_post
  # This API is used for getting Payment Links by PaymentLink ID
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param origin an authorization header. Your origin IP address or URL. Must be configured with AndDone Administration
  # @param x_version x-version
  # @param secure_payment_link_request Secure Payment Link Request
  # @param [Hash] opts the optional parameters
  # @return [PaymentLinkResponse]
  describe 'secure_paymentlinks_details_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for secure_paymentlinks_expirations_post
  # This API is used for to set expired payment link
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param origin an authorization header. Your origin IP address or URL. Must be configured with AndDone Administration
  # @param x_version x-version
  # @param secure_payment_link_request Secure Payment Link Request
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentExpiresResponse]
  describe 'secure_paymentlinks_expirations_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for secure_paymentlinks_id_put
  # This API is used to update Payment Links
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param origin an authorization header. Your origin IP address or URL. Must be configured with AndDone Administration
  # @param x_version x-version
  # @param id PaymentLink identifier
  # @param payment_link_request Payment Link Request
  # @param [Hash] opts the optional parameters
  # @return [PaymentLinkResponse]
  describe 'secure_paymentlinks_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for secure_paymentlinks_post
  # This API is used to create Payment Links
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param origin an authorization header. Your origin IP address or URL. Must be configured with AndDone Administration
  # @param x_version x-version
  # @param payment_link_request Payment Link Request
  # @param [Hash] opts the optional parameters
  # @return [PaymentLinkResponse]
  describe 'secure_paymentlinks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      expect(result_updated.title).to eq(title_update)
    end
  end

end
