=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'openapi_client'

api_instance = OpenapiClient::SecureOutboundPaymentsApi

file = File.read('./config.json')
data_hash = JSON.parse(file)
x_api_key = data_hash['xApiKey']
x_app_key = data_hash['xAppKey']
x_version = data_hash['xVersion']
origin = data_hash['origin']

opts_create = OpenapiClient::PaymentRequestDto.new(
  vendor_id: "Dv4VRa8R",
  payment_method: "Check",
  amount: 70.23,
  bank_detail: BankDetailDto.new(
    account_number: "1234567890",
    routing_number: "121000358"
  ),
  data: PaymentRequestDtoData.new(
    check_number: 1003,
    memo: "Self transfer",
    check_date: "06-19-2025",
    remittance_data: RemittanceDataDto.new(
      headings: [
        HeadingDto.new(
          name: "Item1",
          type: "Date"
        ),
        HeadingDto.new(
          name: "Amount1",
          type: "decimal"
        ),
        HeadingDto.new(
          name: "desc",
          type: "text"
        )
      ]
      rows: [
        [
          RowDto.new(
            name: "Item1",
            value: "04-24-2024",
            type: "Date"
          ),
          RowDto.new(
            name: "Amount1",
            value: "100.12",
            type: "decimal"
          ),
          RowDto.new(
            name: "desc",
            value: "100.12",
            type: "text"
          )
        ],
        [
          RowDto.new(
            name: "Item1",
            value: "04-27-2024",
            type: "Date"
          ),
          RowDto.new(
            name: "Amount1",
            value: "500",
            type: "decimal"
          ),
          RowDto.new(
            name: "desc",
            value: "500",
            type: "text"
          )
        ]
      ]
    )
  )
)

opts_details = OpenapiClient::PaymentRequestDetailDTO.new(
  payment_id: "5a5b9d55-7d93-4b5d-81eb-682adff13562"
)

opts_timeline = OpenapiClient::PaymentTimeLineRequestDto.new(
  payment_id: "5a5b9d55-7d93-4b5d-81eb-682adff13562"
)

opts_search = {}

opts_cancel = OpenapiClient::CancelPaymentRequestDTO.new(
  payment_id: "5a5b9d55-7d93-4b5d-81eb-682adff13562"
)

begin
  # send outbound payment
  result = api_instance.vendorapi_secure_outboundpayments_post(x_api_key, x_app_key, x_version, origin, opts_create)
  p result
  # get outbound payment details
  result = api_instance.vendorapi_secure_outboundpayments_detail_post(x_api_key, x_app_key, x_version, origin, opts_details)
  p result
  # outbound payment timeline
  result = api_instance.vendorapi_secure_outbound_payments_timelines_post(x_api_key, x_app_key, x_version, origin, opts_timeline)
  p result
  # search outbound payments
  result = api_instance.vendorapi_secure_outboundpayments_search_post(x_api_key, x_app_key, x_version, origin, opts_search)
  p result
  # cancel outbound payment
  result = api_instance.vendorapi_secure_outboundpayments_cancel_post(x_api_key, x_app_key, x_version, origin, opts_cancel)
  p result
rescue OpenapiClient::ApiError => e
  puts "Exception when calling Outbound Payments APIs: #{e}"
end

# Unit tests for OpenapiClient::SecureOutboundPaymentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SecureOutboundPaymentsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SecureOutboundPaymentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecureOutboundPaymentsApi' do
    it 'should create an instance of SecureOutboundPaymentsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SecureOutboundPaymentsApi)
    end
  end

  # unit tests for vendorapi_secure_outbound_payments_timelines_post
  # This API gets outbound payment timelines
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param x_version x-version
  # @param origin origin
  # @param payment_time_line_request_dto PaymentTimeLineRequestDto
  # @param [Hash] opts the optional parameters
  # @return [Array<OutboundPaymentTimelineResponseDTOInner>]
  describe 'vendorapi_secure_outbound_payments_timelines_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for vendorapi_secure_outboundpayments_cancel_post
  # This API cancel outbound payment request
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param x_version x-version
  # @param origin origin
  # @param cancel_payment_request_dto CancelPaymentRequestDTO
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'vendorapi_secure_outboundpayments_cancel_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for vendorapi_secure_outboundpayments_detail_post
  # This API fetch outbound payment by paymentId
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param x_version x-version
  # @param origin origin
  # @param payment_request_detail_dto PaymentRequestDetailDTO
  # @param [Hash] opts the optional parameters
  # @return [PaymentDetailResponseDTO]
  describe 'vendorapi_secure_outboundpayments_detail_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for vendorapi_secure_outboundpayments_post
  # This API creates outbound payment request
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param x_version x-version
  # @param origin origin
  # @param payment_request_dto PaymentRequestDto
  # @param [Hash] opts the optional parameters
  # @return [PaymentResponseDto]
  describe 'vendorapi_secure_outboundpayments_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for vendorapi_secure_outboundpayments_search_post
  # This API gets all outbound payment
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param x_version x-version
  # @param origin origin
  # @param [Hash] opts the optional parameters
  # @option opts [String] :vendor_id sets vendorId
  # @option opts [String] :payment_based_id sets paymentBasedId
  # @option opts [String] :payment_id sets paymentId
  # @option opts [String] :vendor_name sets vendorName
  # @option opts [String] :payment_method_type sets paymentMethodType
  # @option opts [String] :payment_method_status sets paymentMethodStatus
  # @option opts [Float] :amount sets amount
  # @option opts [Float] :from_amount sets fromAmount
  # @option opts [Float] :to_amount sets toAmount
  # @option opts [String] :start_date sets startDate
  # @option opts [String] :end_date sets endDate
  # @option opts [String] :search_text sets searchText
  # @option opts [String] :sort_field sets sortField
  # @return [PagePaymentListResponseDTO]
  describe 'vendorapi_secure_outboundpayments_search_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
