=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SecureOrumApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SecureOrumApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SecureOrumApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecureOrumApi' do
    it 'should create an instance of SecureOrumApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SecureOrumApi)
    end
  end

  # unit tests for secure_bankaccounts_details_post
  # This API will request for verified bank account.
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param x_version x-version
  # @param origin origin
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :id The Bank Account Entity Id
  # @option opts [String] :type Set Type
  # @option opts [VerificationEntityRequest] :verification_entity_request Verification Entity
  # @return [Array<VerifyBankAccountResponse>]
  describe 'secure_bankaccounts_details_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for secure_bankaccounts_verify_post
  # This API will request for account verification.
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param x_version x-version
  # @param origin origin
  # @param [Hash] opts the optional parameters
  # @option opts [VerifyBankAccountRequest] :verify_bank_account_request Bank Accout detals
  # @return [Array<VerifyBankAccountResponse>]
  describe 'secure_bankaccounts_verify_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
