=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'openapi_client'

# Setup authorization
OpenapiClient.configure do |config|

end

api_instance = OpenapiClient::SecurePremiumFinanceLiteApi.new

file = File.read('./config.json')
data_hash = JSON.parse(file)
x_api_key = data_hash['xApiKey']
x_app_key = data_hash['xAppKey']
x_version = data_hash['xVersion']
origin = data_hash['origin']

quote_key = ""
payment_link = ""

opts = OpenapiClient::PFLiteSecureQuoteRequest.new(
  merchant_id: x_app_key,
  merchant: OpenapiClient::merchant.new(
    contact_name: "John Doe",
    contact_phone: "0123456789"
  ),
  insured: OpenapiClient::insured.new(
    first_name: "Jane",
    last_name: "Smith",
    mobile_phone_number: null,
    fax_number: null,
    email_address: "test@email.com",
    is_cancellation_warning_via_text_enabled: false,
    address: OpenapiClient::TransactionResponseBillingContactAddress.new(
      address_line1: "1055",
      address_line2: "Broadway Blvd",
      city: "Anchorage",
      state: "AK",
      country: 1,
      postal_code: "64105"
    )
  ),
  program: OpenapiClient::program.new(
    program_id: 82262,
    loan_type: "Personal"
  ),
  policies: [OpenapiClient::policies.new(
    premium: 20000,
    effective_date: "09-30-2024 00:00:00",
    expiration_date: "11-30-2024 00:00:00",
    coverage_type: "FIRE",
    cancel_days: "Item20",
    additional_fees: 0,
    minimum_earned_precent: Null,
    policy_number: "21128675311",
    carrier: OpenapiClient::carrier.new(
      name: "OCCIDENTAL FIRE & CASUALTY CO OF NO",
      best_number: 5555551234,
      unique_id: 23248
    )
  )
]
)

opts_pl = OpenapiClient::PFLiteGetQuoteRequest.new(
  quote_key: quote_key,
  is_pay_in_full: ""
)

opts_link = OpenapiClient::PFLiteGetQuoteRequest.new(
  merchant_token: x_app_key,
  payment_link_id: payment_link
)

begin
  result = api_instance.secure_premium_finance_lite_generate_post(x_api_key, x_app_key, x_version, origin, opts)
  p 'Success - Generate PFL Quote'
  # p result.transaction_id
  quote_key = result.quote_key
  result_pl = api_instance.secure_payments_search_post(x_api_key, x_app_key, x_version, origin)
  p 'Success - Generate PFL Payment Link'
  # p result_search
  payment_link = result_pl.payment_link_id
  result_link = api_instance.secure_paymentsdetails_post(x_api_key, x_app_key, x_version, origin, opts_tm_op)
  # p result_tm_pi.transaction_id
  p 'Success - Get PFL Quotes by Payment Link'
rescue OpenapiClient::ApiError => e
  puts "Exception when calling Payment Intent APIs: #{e}"
end

# Unit tests for OpenapiClient::SecurePaymentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SecurePremiumFinanceLiteApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SecurePremiumFinanceLiteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecurePremiumFinanceLiteApi' do
    it 'should create an instance of PFGenerateQuoteResponse' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PFGenerateQuoteResponse)
    end
  end

end
