=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SecureReportsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
OpenapiClient.configure do |config|
  # Configure API key authorization: x-api-key
  config.api_key['x-api-key'] = 'T3Hj93GzbuhMLiNQg/yJ/yNArhFJeEHoSLyFZ9IBQkY='
  # Uncomment the following line to set a prefix for the API key, e.g. 'Bearer' (defaults to nil)
  # config.api_key_prefix['x-api-key'] = 'Bearer'
  # Configure faraday connection
  config.configure_faraday_connection { |connection| 'YOUR CONNECTION CONFIG PROC' }

  # Configure API key authorization: x-app-key
  config.api_key['x-app-key'] = 'bdYqRMdn'
  # Uncomment the following line to set a prefix for the API key, e.g. 'Bearer' (defaults to nil)
  # config.api_key_prefix['x-app-key'] = 'Bearer'
  # Configure faraday connection
  config.configure_faraday_connection { |connection| 'YOUR CONNECTION CONFIG PROC' }
end

api_instance = OpenapiClient::SecureReportsApi.new

file = File.read('./config.json')
data_hash = JSON.parse(file)
x_api_key = data_hash['xApiKey']
x_app_key = data_hash['xAppKey']
x_version = data_hash['xVersion']
origin = data_hash['origin']

opts = OpenapiClient::ReportDownloadRequest.new(
  report_id: 'KGx1n813',
  date: '05-22-2025'
)
puts opts

begin
  api_instance.secure_reports_downloads_post(x_api_key, x_app_key, x_version, origin, opts)
  p 'Success - Report Download'
rescue OpenapiClient::ApiError => e
  puts "Exception when calling Reports APIs: #{e}"
end

describe 'SecureReportsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SecureReportsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecureReportsApi' do
    it 'should create an instance of SecureReportsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SecureReportsApi)
    end
  end

  # unit tests for secure_reports_downloads_post
  # This API will add system report.
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param origin an authorization header. Your origin IP address or URL. Must be configured with AndDone Administration
  # @param x_version x-version
  # @param [Hash] opts the optional parameters
  # @option opts [ReportDownloadRequest] :report_download_request ReportDownloadRequest
  # @return [nil]
  describe 'secure_reports_downloads_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
