=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'openapi_client'

api_instance = OpenapiClient::SecureRefundsApi

file = File.read('./config.json')
data_hash = JSON.parse(file)
x_api_key = data_hash['xApiKey']
x_app_key = data_hash['xAppKey']
x_version = data_hash['xVersion']
origin = data_hash['origin']

opts_eligible = OpenapiClient::TransactionRefundEligibilityRequest.new(
  transaction_id: "c5ffedc0-d42e-439e-9efa-526528937e98"
)

opts_refund = OpenapiClient::TransactionRefundRequest.new(
  refund_amount: 92.87,
  refund_type: 1,
  transaction_id: "c5ffedc0-d42e-439e-9efa-526528937e98",
  refund_detail: "Refund down payment amount.",
  refund_reason: "Incorrect amount charged."
)

begin
  # get refund eligibility
  result = api_instance.secure_refunds_eligibility_post(x_api_key, x_app_key, x_version, origin, opts_eligible)
  p result
  # secure refund
  result = api_instance.secure_refunds_post(x_api_key, x_app_key, x_version, origin, opts_refund)
  p result
rescue OpenapiClient::ApiError => e
  puts "Exception when calling Secure Refund APIs: #{e}"
end

# Unit tests for OpenapiClient::SecureRefundsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SecureRefundsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SecureRefundsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecureRefundsApi' do
    it 'should create an instance of SecureRefundsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SecureRefundsApi)
    end
  end

  # unit tests for secure_refunds_eligibility_post
  # This API return refund eligibility of a transaction.
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param origin an authorization header. Your origin IP address or URL. Must be configured with AndDone Administration
  # @param x_version x-version
  # @param transaction_refund_eligibility_request refund Detail
  # @param [Hash] opts the optional parameters
  # @return [RefundEligibility]
  describe 'secure_refunds_eligibility_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for secure_refunds_post
  # This API return refund a transaction.
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param origin an authorization header. Your origin IP address or URL. Must be configured with AndDone Administration
  # @param x_version x-version
  # @param transaction_refund_request refund Detail
  # @param [Hash] opts the optional parameters
  # @return [TransactionResponse]
  describe 'secure_refunds_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
