=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SecurePaymentIntentApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SecurePaymentIntentApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SecurePaymentIntentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecurePaymentIntentApi' do
    it 'should create an instance of SecurePaymentIntentApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SecurePaymentIntentApi)
    end
  end

  # unit tests for secure_paymentintents_expirations_post
  # This API expires the payment Intent or link.
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param x_version x-version
  # @param origin origin
  # @param id Payment Intent Id
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentExpiresResponse]
  describe 'secure_paymentintents_expirations_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for secure_paymentintents_post
  # This API is use to create Secure payment Intent.
  # @param x_api_key an authorization header
  # @param x_app_key an authorization header
  # @param x_version x-version
  # @param origin origin
  # @param [Hash] opts the optional parameters
  # @option opts [PaymentIntentRequest] :payment_intent_request Payment Intent Request
  # @return [PaymentIntentResponse]
  describe 'secure_paymentintents_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
