=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PaymentIntentRequestReferenceDataListInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PaymentIntentRequestReferenceDataListInner do
  let(:instance) { OpenapiClient::PaymentIntentRequestReferenceDataListInner.new }

  describe 'test an instance of PaymentIntentRequestReferenceDataListInner' do
    it 'should create an instance of PaymentIntentRequestReferenceDataListInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PaymentIntentRequestReferenceDataListInner)
    end
  end

  describe 'test attribute "reference_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["QuoteNumber", "AccountNumber", "PolicyNumber", "InvoiceNumber", "OtherNumber"])
      # validator.allowable_values.each do |value|
      #   expect { instance.reference_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "reference_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reference_key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
