=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PaymentLinkResponseDisplaySettingsIntent
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PaymentLinkResponseDisplaySettingsIntent do
  let(:instance) { OpenapiClient::PaymentLinkResponseDisplaySettingsIntent.new }

  describe 'test an instance of PaymentLinkResponseDisplaySettingsIntent' do
    it 'should create an instance of PaymentLinkResponseDisplaySettingsIntent' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PaymentLinkResponseDisplaySettingsIntent)
    end
  end

  describe 'test attribute "payment_types"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["CreditCard", "DebitCard", "ACH"])
      # validator.allowable_values.each do |value|
      #   expect { instance.payment_types = value }.not_to raise_error
      # end
    end
  end

end
