=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PaymentLinkRequestCallbackParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PaymentLinkRequestCallbackParameters do
  let(:instance) { OpenapiClient::PaymentLinkRequestCallbackParameters.new }

  describe 'test an instance of PaymentLinkRequestCallbackParameters' do
    it 'should create an instance of PaymentLinkRequestCallbackParameters' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PaymentLinkRequestCallbackParameters)
    end
  end

  describe 'test attribute "callback_api_url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "callback_message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
