=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PaymentLinkRequestSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PaymentLinkRequestSettings do
  let(:instance) { OpenapiClient::PaymentLinkRequestSettings.new }

  describe 'test an instance of PaymentLinkRequestSettings' do
    it 'should create an instance of PaymentLinkRequestSettings' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PaymentLinkRequestSettings)
    end
  end

  describe 'test attribute "additional_details_preference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Float', [1, 2, 3])
      # validator.allowable_values.each do |value|
      #   expect { instance.additional_details_preference = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "intent"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
