=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PFEndorsementRequestQuoteInsured
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PFEndorsementRequestQuoteInsured do
  let(:instance) { OpenapiClient::PFEndorsementRequestQuoteInsured.new }

  describe 'test an instance of PFEndorsementRequestQuoteInsured' do
    it 'should create an instance of PFEndorsementRequestQuoteInsured' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PFEndorsementRequestQuoteInsured)
    end
  end

  describe 'test attribute "agent_customer_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "care_of"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "address"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
