=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PFEndorsementRequestQuoteDetailsRecurringACH
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PFEndorsementRequestQuoteDetailsRecurringACH do
  let(:instance) { OpenapiClient::PFEndorsementRequestQuoteDetailsRecurringACH.new }

  describe 'test an instance of PFEndorsementRequestQuoteDetailsRecurringACH' do
    it 'should create an instance of PFEndorsementRequestQuoteDetailsRecurringACH' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PFEndorsementRequestQuoteDetailsRecurringACH)
    end
  end

  describe 'test attribute "enroll_recurring_ach"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "bank_routing_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "bank_acct_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_checking_account"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ach_disclosure"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
