=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner do
  let(:instance) { OpenapiClient::PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner.new }

  describe 'test an instance of PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner' do
    it 'should create an instance of PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner)
    end
  end

  describe 'test attribute "pay_to"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "payment_method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "funding_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "bank_routing_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "bank_acct_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_checking_account"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "funding_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
