=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PFLitePaymentLinkRequestSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PFLitePaymentLinkRequestSettings do
  let(:instance) { OpenapiClient::PFLitePaymentLinkRequestSettings.new }

  describe 'test an instance of PFLitePaymentLinkRequestSettings' do
    it 'should create an instance of PFLitePaymentLinkRequestSettings' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PFLitePaymentLinkRequestSettings)
    end
  end

  describe 'test attribute "selected_customer_fields"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "additional_details_preference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AskShopper", "ManualEnter", "NoAdditionalDetails"])
      # validator.allowable_values.each do |value|
      #   expect { instance.additional_details_preference = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "intent"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
