=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PFUpdatePFARequestDTO
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PFUpdatePFARequestDTO do
  let(:instance) { OpenapiClient::PFUpdatePFARequestDTO.new }

  describe 'test an instance of PFUpdatePFARequestDTO' do
    it 'should create an instance of PFUpdatePFARequestDTO' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PFUpdatePFARequestDTO)
    end
  end

  describe 'test attribute "quote_key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
