=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::QuoteRequestPoliciesInnerPolicyFeesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::QuoteRequestPoliciesInnerPolicyFeesInner do
  let(:instance) { OpenapiClient::QuoteRequestPoliciesInnerPolicyFeesInner.new }

  describe 'test an instance of QuoteRequestPoliciesInnerPolicyFeesInner' do
    it 'should create an instance of QuoteRequestPoliciesInnerPolicyFeesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::QuoteRequestPoliciesInnerPolicyFeesInner)
    end
  end

  describe 'test attribute "fee_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "fee_amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
