=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::QuoteRequestDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::QuoteRequestDetails do
  let(:instance) { OpenapiClient::QuoteRequestDetails.new }

  describe 'test an instance of QuoteRequestDetails' do
    it 'should create an instance of QuoteRequestDetails' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::QuoteRequestDetails)
    end
  end

  describe 'test attribute "coupon_invoice_printed"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "installments"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "program_ids"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "batch_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "commercial"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NA", "Commercial", "Personal"])
      # validator.allowable_values.each do |value|
      #   expect { instance.commercial = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "coupon"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NA", "PaymentsInvoices", "CouponsBook"])
      # validator.allowable_values.each do |value|
      #   expect { instance.coupon = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "interval"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NA", "Monthly", "Bimonthly", "Quarterly", "SemiAnnual", "Annual", "Z", "Y", "X", "W"])
      # validator.allowable_values.each do |value|
      #   expect { instance.interval = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "down_payment_method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ACH", "CC", "BOTH"])
      # validator.allowable_values.each do |value|
      #   expect { instance.down_payment_method = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "down_payment_paid_by"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NA", "Agent", "Insured"])
      # validator.allowable_values.each do |value|
      #   expect { instance.down_payment_paid_by = value }.not_to raise_error
      # end
    end
  end

end
