=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SecurePaymentBatchDetailsRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SecurePaymentBatchDetailsRequest do
  let(:instance) { OpenapiClient::SecurePaymentBatchDetailsRequest.new }

  describe 'test an instance of SecurePaymentBatchDetailsRequest' do
    it 'should create an instance of SecurePaymentBatchDetailsRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SecurePaymentBatchDetailsRequest)
    end
  end

  describe 'test attribute "batch_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
