=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TokenLinkSecureRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TokenLinkSecureRequest do
  let(:instance) { OpenapiClient::TokenLinkSecureRequest.new }

  describe 'test an instance of TokenLinkSecureRequest' do
    it 'should create an instance of TokenLinkSecureRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::TokenLinkSecureRequest)
    end
  end

  describe 'test attribute "merchant_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "expire_in"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "expire_in_unit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Minutes", "Hours", "Days", "Weeks"])
      # validator.allowable_values.each do |value|
      #   expect { instance.expire_in_unit = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "response_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["OnScreen", "CallBack"])
      # validator.allowable_values.each do |value|
      #   expect { instance.response_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "intent"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "callback_parameters"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "customers"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
