=begin
#Secure API

#Secure API's

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TokenLinkResponseIntent
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TokenLinkResponseIntent do
  let(:instance) { OpenapiClient::TokenLinkResponseIntent.new }

  describe 'test an instance of TokenLinkResponseIntent' do
    it 'should create an instance of TokenLinkResponseIntent' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::TokenLinkResponseIntent)
    end
  end

  describe 'test attribute "payment_types"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["NotDefined", "ACH", "CreditCard", "DebitCard", "RTP"])
      # validator.allowable_values.each do |value|
      #   expect { instance.payment_types = value }.not_to raise_error
      # end
    end
  end

end
