=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::VendorTimelineResponseListInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::VendorTimelineResponseListInner do
  let(:instance) { OpenapiClient::VendorTimelineResponseListInner.new }

  describe 'test an instance of VendorTimelineResponseListInner' do
    it 'should create an instance of VendorTimelineResponseListInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::VendorTimelineResponseListInner)
    end
  end

  describe 'test attribute "vendor_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NA", "Reviewing", "Approved", "Denied", "Suspended", "Deleted"])
      # validator.allowable_values.each do |value|
      #   expect { instance.vendor_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "event_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "created_by"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
