=begin
#Secure API

#Secure API

The version of the OpenAPI document: 2.3

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'cgi'

module OpenapiClient
  class SecurePaymentsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # This API gets Secure payment by search criteria for the merchant.
    # @param x_api_key [String] an authorization header
    # @param x_app_key [String] an authorization header
    # @param x_version [Float] x-version
    # @param origin [String] origin
    # @param [Hash] opts the optional parameters
    # @option opts [String] :start_date Start date for the transaction search
    # @option opts [String] :end_date End date for the transaction search
    # @option opts [String] :transaction_ids Transaction identifier
    # @option opts [String] :reference_transaction_id Reference transaction identifier
    # @option opts [String] :transaction_statuses Status of the transaction
    # @option opts [String] :customer_ids Customer IDs associated with the transaction
    # @option opts [String] :transaction_type Type of the transaction
    # @option opts [String] :auth_code Authorization code of the transaction
    # @option opts [String] :card_holder_name Name of the cardholder
    # @option opts [String] :shopper_name ShopperName of the cardholder
    # @option opts [Float] :amount Transaction amount
    # @option opts [Float] :from_amount Minimum transaction amount
    # @option opts [Float] :to_amount Maximum transaction amount
    # @option opts [String] :channel_types Channel types used for the transaction
    # @option opts [String] :mask_account Masked account number
    # @option opts [String] :customer_name Name of the customer
    # @option opts [String] :recurring_id Recurring payment ID
    # @option opts [String] :reference_no Reference number
    # @option opts [Boolean] :export_to_csv Export To Csv
    # @option opts [Boolean] :export_to_pdf Export To PDF
    # @option opts [String] :transaction_origins Type of origin used in the transaction
    # @option opts [String] :transaction_source_type Transaction source type of the transaction
    # @option opts [Integer] :source_id Set SourceId
    # @option opts [String] :trace_numbers TraceNumbers associated with the transaction
    # @option opts [String] :bin_number BinNumber
    # @option opts [String] :process_method Process Method used for the transaction
    # @option opts [String] :search_text SearchText of the transaction
    # @option opts [String] :merchant_reference Merchant Reference of the transaction
    # @option opts [String] :additional_fields Additional Fields
    # @option opts [String] :additional_field_value AdditionalFieldValue
    # @option opts [String] :payment_method Payment Method
    # @option opts [String] :account_alias Set AccountAlias
    # @option opts [Boolean] :is_paid Set IsPaid
    # @option opts [String] :payment_types Type of payment used in the transaction
    # @option opts [String] :merchant_id Search with Merchant Id
    # @option opts [String] :payment_categories Set PaymentCategories
    # @option opts [Boolean] :suppress_technology_fee SuppressTechnologyFee
    # @option opts [String] :batch_id BatchId
    # @option opts [String] :sort_field SortField
    # @option opts [Integer] :start_row Set StartRow
    # @option opts [Integer] :page_size Set PageSize
    # @option opts [Boolean] :asc Set Asc
    # @return [nil]
    def secure_payments_export_post(x_api_key, x_app_key, x_version, origin, opts = {})
      secure_payments_export_post_with_http_info(x_api_key, x_app_key, x_version, origin, opts)
      nil
    end

    # This API gets Secure payment by search criteria for the merchant.
    # @param x_api_key [String] an authorization header
    # @param x_app_key [String] an authorization header
    # @param x_version [Float] x-version
    # @param origin [String] origin
    # @param [Hash] opts the optional parameters
    # @option opts [String] :start_date Start date for the transaction search
    # @option opts [String] :end_date End date for the transaction search
    # @option opts [String] :transaction_ids Transaction identifier
    # @option opts [String] :reference_transaction_id Reference transaction identifier
    # @option opts [String] :transaction_statuses Status of the transaction
    # @option opts [String] :customer_ids Customer IDs associated with the transaction
    # @option opts [String] :transaction_type Type of the transaction
    # @option opts [String] :auth_code Authorization code of the transaction
    # @option opts [String] :card_holder_name Name of the cardholder
    # @option opts [String] :shopper_name ShopperName of the cardholder
    # @option opts [Float] :amount Transaction amount
    # @option opts [Float] :from_amount Minimum transaction amount
    # @option opts [Float] :to_amount Maximum transaction amount
    # @option opts [String] :channel_types Channel types used for the transaction
    # @option opts [String] :mask_account Masked account number
    # @option opts [String] :customer_name Name of the customer
    # @option opts [String] :recurring_id Recurring payment ID
    # @option opts [String] :reference_no Reference number
    # @option opts [Boolean] :export_to_csv Export To Csv
    # @option opts [Boolean] :export_to_pdf Export To PDF
    # @option opts [String] :transaction_origins Type of origin used in the transaction
    # @option opts [String] :transaction_source_type Transaction source type of the transaction
    # @option opts [Integer] :source_id Set SourceId
    # @option opts [String] :trace_numbers TraceNumbers associated with the transaction
    # @option opts [String] :bin_number BinNumber
    # @option opts [String] :process_method Process Method used for the transaction
    # @option opts [String] :search_text SearchText of the transaction
    # @option opts [String] :merchant_reference Merchant Reference of the transaction
    # @option opts [String] :additional_fields Additional Fields
    # @option opts [String] :additional_field_value AdditionalFieldValue
    # @option opts [String] :payment_method Payment Method
    # @option opts [String] :account_alias Set AccountAlias
    # @option opts [Boolean] :is_paid Set IsPaid
    # @option opts [String] :payment_types Type of payment used in the transaction
    # @option opts [String] :merchant_id Search with Merchant Id
    # @option opts [String] :payment_categories Set PaymentCategories
    # @option opts [Boolean] :suppress_technology_fee SuppressTechnologyFee
    # @option opts [String] :batch_id BatchId
    # @option opts [String] :sort_field SortField
    # @option opts [Integer] :start_row Set StartRow
    # @option opts [Integer] :page_size Set PageSize
    # @option opts [Boolean] :asc Set Asc
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def secure_payments_export_post_with_http_info(x_api_key, x_app_key, x_version, origin, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SecurePaymentsApi.secure_payments_export_post ...'
      end
      # verify the required parameter 'x_api_key' is set
      if @api_client.config.client_side_validation && x_api_key.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_key' when calling SecurePaymentsApi.secure_payments_export_post"
      end
      # verify the required parameter 'x_app_key' is set
      if @api_client.config.client_side_validation && x_app_key.nil?
        fail ArgumentError, "Missing the required parameter 'x_app_key' when calling SecurePaymentsApi.secure_payments_export_post"
      end
      # verify the required parameter 'x_version' is set
      if @api_client.config.client_side_validation && x_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_version' when calling SecurePaymentsApi.secure_payments_export_post"
      end
      # verify the required parameter 'origin' is set
      if @api_client.config.client_side_validation && origin.nil?
        fail ArgumentError, "Missing the required parameter 'origin' when calling SecurePaymentsApi.secure_payments_export_post"
      end
      allowable_values = ["Sale", "VerifyOnly", "ForceSale", "Adjust", "Activate", "Deactivate", "Reload", "Refund", "Inquire", "ReverseAuth"]
      if @api_client.config.client_side_validation && opts[:'transaction_type'] && !allowable_values.include?(opts[:'transaction_type'])
        fail ArgumentError, "invalid value for \"transaction_type\", must be one of #{allowable_values}"
      end
      allowable_values = ["Independent", "Invoice", "Order", "PaymentPlan"]
      if @api_client.config.client_side_validation && opts[:'transaction_source_type'] && !allowable_values.include?(opts[:'transaction_source_type'])
        fail ArgumentError, "invalid value for \"transaction_source_type\", must be one of #{allowable_values}"
      end
      allowable_values = ["NotDefined", "ACH", "CardNotPresent"]
      if @api_client.config.client_side_validation && opts[:'process_method'] && !allowable_values.include?(opts[:'process_method'])
        fail ArgumentError, "invalid value for \"process_method\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/secure/payments/export'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'startDate'] = opts[:'start_date'] if !opts[:'start_date'].nil?
      query_params[:'endDate'] = opts[:'end_date'] if !opts[:'end_date'].nil?
      query_params[:'transactionIds'] = opts[:'transaction_ids'] if !opts[:'transaction_ids'].nil?
      query_params[:'referenceTransactionId'] = opts[:'reference_transaction_id'] if !opts[:'reference_transaction_id'].nil?
      query_params[:'transactionStatuses'] = opts[:'transaction_statuses'] if !opts[:'transaction_statuses'].nil?
      query_params[:'customerIds'] = opts[:'customer_ids'] if !opts[:'customer_ids'].nil?
      query_params[:'transactionType'] = opts[:'transaction_type'] if !opts[:'transaction_type'].nil?
      query_params[:'authCode'] = opts[:'auth_code'] if !opts[:'auth_code'].nil?
      query_params[:'cardHolderName'] = opts[:'card_holder_name'] if !opts[:'card_holder_name'].nil?
      query_params[:'shopperName'] = opts[:'shopper_name'] if !opts[:'shopper_name'].nil?
      query_params[:'amount'] = opts[:'amount'] if !opts[:'amount'].nil?
      query_params[:'fromAmount'] = opts[:'from_amount'] if !opts[:'from_amount'].nil?
      query_params[:'toAmount'] = opts[:'to_amount'] if !opts[:'to_amount'].nil?
      query_params[:'channelTypes'] = opts[:'channel_types'] if !opts[:'channel_types'].nil?
      query_params[:'maskAccount'] = opts[:'mask_account'] if !opts[:'mask_account'].nil?
      query_params[:'customerName'] = opts[:'customer_name'] if !opts[:'customer_name'].nil?
      query_params[:'recurringId'] = opts[:'recurring_id'] if !opts[:'recurring_id'].nil?
      query_params[:'referenceNo'] = opts[:'reference_no'] if !opts[:'reference_no'].nil?
      query_params[:'exportToCsv'] = opts[:'export_to_csv'] if !opts[:'export_to_csv'].nil?
      query_params[:'exportToPDF'] = opts[:'export_to_pdf'] if !opts[:'export_to_pdf'].nil?
      query_params[:'transactionOrigins'] = opts[:'transaction_origins'] if !opts[:'transaction_origins'].nil?
      query_params[:'transactionSourceType'] = opts[:'transaction_source_type'] if !opts[:'transaction_source_type'].nil?
      query_params[:'sourceId'] = opts[:'source_id'] if !opts[:'source_id'].nil?
      query_params[:'traceNumbers'] = opts[:'trace_numbers'] if !opts[:'trace_numbers'].nil?
      query_params[:'binNumber'] = opts[:'bin_number'] if !opts[:'bin_number'].nil?
      query_params[:'processMethod'] = opts[:'process_method'] if !opts[:'process_method'].nil?
      query_params[:'searchText'] = opts[:'search_text'] if !opts[:'search_text'].nil?
      query_params[:'merchantReference'] = opts[:'merchant_reference'] if !opts[:'merchant_reference'].nil?
      query_params[:'additionalFields'] = opts[:'additional_fields'] if !opts[:'additional_fields'].nil?
      query_params[:'additionalFieldValue'] = opts[:'additional_field_value'] if !opts[:'additional_field_value'].nil?
      query_params[:'paymentMethod'] = opts[:'payment_method'] if !opts[:'payment_method'].nil?
      query_params[:'accountAlias'] = opts[:'account_alias'] if !opts[:'account_alias'].nil?
      query_params[:'isPaid'] = opts[:'is_paid'] if !opts[:'is_paid'].nil?
      query_params[:'paymentTypes'] = opts[:'payment_types'] if !opts[:'payment_types'].nil?
      query_params[:'merchantId'] = opts[:'merchant_id'] if !opts[:'merchant_id'].nil?
      query_params[:'paymentCategories'] = opts[:'payment_categories'] if !opts[:'payment_categories'].nil?
      query_params[:'suppressTechnologyFee'] = opts[:'suppress_technology_fee'] if !opts[:'suppress_technology_fee'].nil?
      query_params[:'batchId'] = opts[:'batch_id'] if !opts[:'batch_id'].nil?
      query_params[:'sortField'] = opts[:'sort_field'] if !opts[:'sort_field'].nil?
      query_params[:'startRow'] = opts[:'start_row'] if !opts[:'start_row'].nil?
      query_params[:'pageSize'] = opts[:'page_size'] if !opts[:'page_size'].nil?
      query_params[:'asc'] = opts[:'asc'] if !opts[:'asc'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/csv']) unless header_params['Accept']
      header_params[:'x-api-key'] = x_api_key
      header_params[:'x-app-key'] = x_app_key
      header_params[:'x-version'] = x_version
      header_params[:'origin'] = origin

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"SecurePaymentsApi.secure_payments_export_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SecurePaymentsApi#secure_payments_export_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # This API posts new Secure payment request for the merchant.
    # @param x_api_key [String] an authorization header
    # @param x_app_key [String] an authorization header
    # @param x_version [Float] x-version
    # @param origin [String] origin
    # @param payment_request [PaymentRequest] Payment Detail
    # @param [Hash] opts the optional parameters
    # @return [TransactionDetailResponse]
    def secure_payments_post(x_api_key, x_app_key, x_version, origin, payment_request, opts = {})
      data, _status_code, _headers = secure_payments_post_with_http_info(x_api_key, x_app_key, x_version, origin, payment_request, opts)
      data
    end

    # This API posts new Secure payment request for the merchant.
    # @param x_api_key [String] an authorization header
    # @param x_app_key [String] an authorization header
    # @param x_version [Float] x-version
    # @param origin [String] origin
    # @param payment_request [PaymentRequest] Payment Detail
    # @param [Hash] opts the optional parameters
    # @return [Array<(TransactionDetailResponse, Integer, Hash)>] TransactionDetailResponse data, response status code and response headers
    def secure_payments_post_with_http_info(x_api_key, x_app_key, x_version, origin, payment_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SecurePaymentsApi.secure_payments_post ...'
      end
      # verify the required parameter 'x_api_key' is set
      if @api_client.config.client_side_validation && x_api_key.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_key' when calling SecurePaymentsApi.secure_payments_post"
      end
      # verify the required parameter 'x_app_key' is set
      if @api_client.config.client_side_validation && x_app_key.nil?
        fail ArgumentError, "Missing the required parameter 'x_app_key' when calling SecurePaymentsApi.secure_payments_post"
      end
      # verify the required parameter 'x_version' is set
      if @api_client.config.client_side_validation && x_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_version' when calling SecurePaymentsApi.secure_payments_post"
      end
      # verify the required parameter 'origin' is set
      if @api_client.config.client_side_validation && origin.nil?
        fail ArgumentError, "Missing the required parameter 'origin' when calling SecurePaymentsApi.secure_payments_post"
      end
      # verify the required parameter 'payment_request' is set
      if @api_client.config.client_side_validation && payment_request.nil?
        fail ArgumentError, "Missing the required parameter 'payment_request' when calling SecurePaymentsApi.secure_payments_post"
      end
      # resource path
      local_var_path = '/secure/payments'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'x-api-key'] = x_api_key
      header_params[:'x-app-key'] = x_app_key
      header_params[:'x-version'] = x_version
      header_params[:'origin'] = origin

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(payment_request)

      # return_type
      return_type = opts[:debug_return_type] || 'TransactionDetailResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"SecurePaymentsApi.secure_payments_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SecurePaymentsApi#secure_payments_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # This API gets Secure payment by search criteria for the merchant.
    # @param x_api_key [String] an authorization header
    # @param x_app_key [String] an authorization header
    # @param x_version [Float] x-version
    # @param origin [String] origin
    # @param [Hash] opts the optional parameters
    # @option opts [String] :start_date Start date for the transaction search
    # @option opts [String] :end_date End date for the transaction search
    # @option opts [String] :transaction_ids Transaction identifier
    # @option opts [String] :reference_transaction_id Reference transaction identifier
    # @option opts [String] :transaction_statuses Status of the transaction
    # @option opts [String] :customer_ids Customer IDs associated with the transaction
    # @option opts [String] :transaction_type Type of the transaction
    # @option opts [String] :auth_code Authorization code of the transaction
    # @option opts [String] :card_holder_name Name of the cardholder
    # @option opts [String] :shopper_name ShopperName of the cardholder
    # @option opts [Float] :amount Transaction amount
    # @option opts [Float] :from_amount Minimum transaction amount
    # @option opts [Float] :to_amount Maximum transaction amount
    # @option opts [String] :channel_types Channel types used for the transaction
    # @option opts [String] :mask_account Masked account number
    # @option opts [String] :customer_name Name of the customer
    # @option opts [String] :recurring_id Recurring payment ID
    # @option opts [String] :reference_no Reference number
    # @option opts [Boolean] :export_to_csv Export To Csv
    # @option opts [Boolean] :export_to_pdf Export To PDF
    # @option opts [String] :transaction_origins Type of origin used in the transaction
    # @option opts [String] :transaction_source_type Transaction source type of the transaction
    # @option opts [Integer] :source_id Set SourceId
    # @option opts [String] :trace_numbers TraceNumbers associated with the transaction
    # @option opts [String] :bin_number BinNumber
    # @option opts [String] :process_method Process Method used for the transaction
    # @option opts [String] :search_text SearchText of the transaction
    # @option opts [String] :merchant_reference Merchant Reference of the transaction
    # @option opts [String] :additional_fields Additional Fields
    # @option opts [String] :additional_field_value AdditionalFieldValue
    # @option opts [String] :payment_method Payment Method
    # @option opts [String] :account_alias Set AccountAlias
    # @option opts [Boolean] :is_paid Set IsPaid
    # @option opts [String] :payment_types Type of payment used in the transaction
    # @option opts [String] :merchant_id Search with Merchant Id
    # @option opts [String] :payment_categories Set PaymentCategories
    # @option opts [Boolean] :suppress_technology_fee SuppressTechnologyFee
    # @option opts [String] :batch_id BatchId
    # @option opts [Boolean] :transactions_count Set whether to return only the transactions count
    # @option opts [String] :sort_field SortField
    # @option opts [Integer] :start_row Set StartRow
    # @option opts [Integer] :page_size Set PageSize
    # @option opts [Boolean] :asc Set Asc
    # @return [MerchantTransactionEntityResponse]
    def secure_payments_search_post(x_api_key, x_app_key, x_version, origin, opts = {})
      data, _status_code, _headers = secure_payments_search_post_with_http_info(x_api_key, x_app_key, x_version, origin, opts)
      data
    end

    # This API gets Secure payment by search criteria for the merchant.
    # @param x_api_key [String] an authorization header
    # @param x_app_key [String] an authorization header
    # @param x_version [Float] x-version
    # @param origin [String] origin
    # @param [Hash] opts the optional parameters
    # @option opts [String] :start_date Start date for the transaction search
    # @option opts [String] :end_date End date for the transaction search
    # @option opts [String] :transaction_ids Transaction identifier
    # @option opts [String] :reference_transaction_id Reference transaction identifier
    # @option opts [String] :transaction_statuses Status of the transaction
    # @option opts [String] :customer_ids Customer IDs associated with the transaction
    # @option opts [String] :transaction_type Type of the transaction
    # @option opts [String] :auth_code Authorization code of the transaction
    # @option opts [String] :card_holder_name Name of the cardholder
    # @option opts [String] :shopper_name ShopperName of the cardholder
    # @option opts [Float] :amount Transaction amount
    # @option opts [Float] :from_amount Minimum transaction amount
    # @option opts [Float] :to_amount Maximum transaction amount
    # @option opts [String] :channel_types Channel types used for the transaction
    # @option opts [String] :mask_account Masked account number
    # @option opts [String] :customer_name Name of the customer
    # @option opts [String] :recurring_id Recurring payment ID
    # @option opts [String] :reference_no Reference number
    # @option opts [Boolean] :export_to_csv Export To Csv
    # @option opts [Boolean] :export_to_pdf Export To PDF
    # @option opts [String] :transaction_origins Type of origin used in the transaction
    # @option opts [String] :transaction_source_type Transaction source type of the transaction
    # @option opts [Integer] :source_id Set SourceId
    # @option opts [String] :trace_numbers TraceNumbers associated with the transaction
    # @option opts [String] :bin_number BinNumber
    # @option opts [String] :process_method Process Method used for the transaction
    # @option opts [String] :search_text SearchText of the transaction
    # @option opts [String] :merchant_reference Merchant Reference of the transaction
    # @option opts [String] :additional_fields Additional Fields
    # @option opts [String] :additional_field_value AdditionalFieldValue
    # @option opts [String] :payment_method Payment Method
    # @option opts [String] :account_alias Set AccountAlias
    # @option opts [Boolean] :is_paid Set IsPaid
    # @option opts [String] :payment_types Type of payment used in the transaction
    # @option opts [String] :merchant_id Search with Merchant Id
    # @option opts [String] :payment_categories Set PaymentCategories
    # @option opts [Boolean] :suppress_technology_fee SuppressTechnologyFee
    # @option opts [String] :batch_id BatchId
    # @option opts [Boolean] :transactions_count Set whether to return only the transactions count
    # @option opts [String] :sort_field SortField
    # @option opts [Integer] :start_row Set StartRow
    # @option opts [Integer] :page_size Set PageSize
    # @option opts [Boolean] :asc Set Asc
    # @return [Array<(MerchantTransactionEntityResponse, Integer, Hash)>] MerchantTransactionEntityResponse data, response status code and response headers
    def secure_payments_search_post_with_http_info(x_api_key, x_app_key, x_version, origin, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SecurePaymentsApi.secure_payments_search_post ...'
      end
      # verify the required parameter 'x_api_key' is set
      if @api_client.config.client_side_validation && x_api_key.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_key' when calling SecurePaymentsApi.secure_payments_search_post"
      end
      # verify the required parameter 'x_app_key' is set
      if @api_client.config.client_side_validation && x_app_key.nil?
        fail ArgumentError, "Missing the required parameter 'x_app_key' when calling SecurePaymentsApi.secure_payments_search_post"
      end
      # verify the required parameter 'x_version' is set
      if @api_client.config.client_side_validation && x_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_version' when calling SecurePaymentsApi.secure_payments_search_post"
      end
      # verify the required parameter 'origin' is set
      if @api_client.config.client_side_validation && origin.nil?
        fail ArgumentError, "Missing the required parameter 'origin' when calling SecurePaymentsApi.secure_payments_search_post"
      end
      allowable_values = ["Sale", "VerifyOnly", "ForceSale", "Adjust", "Activate", "Deactivate", "Reload", "Refund", "Inquire", "ReverseAuth"]
      if @api_client.config.client_side_validation && opts[:'transaction_type'] && !allowable_values.include?(opts[:'transaction_type'])
        fail ArgumentError, "invalid value for \"transaction_type\", must be one of #{allowable_values}"
      end
      allowable_values = ["Independent", "Invoice", "Order", "PaymentPlan"]
      if @api_client.config.client_side_validation && opts[:'transaction_source_type'] && !allowable_values.include?(opts[:'transaction_source_type'])
        fail ArgumentError, "invalid value for \"transaction_source_type\", must be one of #{allowable_values}"
      end
      allowable_values = ["NotDefined", "ACH", "CardNotPresent"]
      if @api_client.config.client_side_validation && opts[:'process_method'] && !allowable_values.include?(opts[:'process_method'])
        fail ArgumentError, "invalid value for \"process_method\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/secure/payments/search'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'startDate'] = opts[:'start_date'] if !opts[:'start_date'].nil?
      query_params[:'endDate'] = opts[:'end_date'] if !opts[:'end_date'].nil?
      query_params[:'transactionIds'] = opts[:'transaction_ids'] if !opts[:'transaction_ids'].nil?
      query_params[:'referenceTransactionId'] = opts[:'reference_transaction_id'] if !opts[:'reference_transaction_id'].nil?
      query_params[:'transactionStatuses'] = opts[:'transaction_statuses'] if !opts[:'transaction_statuses'].nil?
      query_params[:'customerIds'] = opts[:'customer_ids'] if !opts[:'customer_ids'].nil?
      query_params[:'transactionType'] = opts[:'transaction_type'] if !opts[:'transaction_type'].nil?
      query_params[:'authCode'] = opts[:'auth_code'] if !opts[:'auth_code'].nil?
      query_params[:'cardHolderName'] = opts[:'card_holder_name'] if !opts[:'card_holder_name'].nil?
      query_params[:'shopperName'] = opts[:'shopper_name'] if !opts[:'shopper_name'].nil?
      query_params[:'amount'] = opts[:'amount'] if !opts[:'amount'].nil?
      query_params[:'fromAmount'] = opts[:'from_amount'] if !opts[:'from_amount'].nil?
      query_params[:'toAmount'] = opts[:'to_amount'] if !opts[:'to_amount'].nil?
      query_params[:'channelTypes'] = opts[:'channel_types'] if !opts[:'channel_types'].nil?
      query_params[:'maskAccount'] = opts[:'mask_account'] if !opts[:'mask_account'].nil?
      query_params[:'customerName'] = opts[:'customer_name'] if !opts[:'customer_name'].nil?
      query_params[:'recurringId'] = opts[:'recurring_id'] if !opts[:'recurring_id'].nil?
      query_params[:'referenceNo'] = opts[:'reference_no'] if !opts[:'reference_no'].nil?
      query_params[:'exportToCsv'] = opts[:'export_to_csv'] if !opts[:'export_to_csv'].nil?
      query_params[:'exportToPDF'] = opts[:'export_to_pdf'] if !opts[:'export_to_pdf'].nil?
      query_params[:'transactionOrigins'] = opts[:'transaction_origins'] if !opts[:'transaction_origins'].nil?
      query_params[:'transactionSourceType'] = opts[:'transaction_source_type'] if !opts[:'transaction_source_type'].nil?
      query_params[:'sourceId'] = opts[:'source_id'] if !opts[:'source_id'].nil?
      query_params[:'traceNumbers'] = opts[:'trace_numbers'] if !opts[:'trace_numbers'].nil?
      query_params[:'binNumber'] = opts[:'bin_number'] if !opts[:'bin_number'].nil?
      query_params[:'processMethod'] = opts[:'process_method'] if !opts[:'process_method'].nil?
      query_params[:'searchText'] = opts[:'search_text'] if !opts[:'search_text'].nil?
      query_params[:'merchantReference'] = opts[:'merchant_reference'] if !opts[:'merchant_reference'].nil?
      query_params[:'additionalFields'] = opts[:'additional_fields'] if !opts[:'additional_fields'].nil?
      query_params[:'additionalFieldValue'] = opts[:'additional_field_value'] if !opts[:'additional_field_value'].nil?
      query_params[:'paymentMethod'] = opts[:'payment_method'] if !opts[:'payment_method'].nil?
      query_params[:'accountAlias'] = opts[:'account_alias'] if !opts[:'account_alias'].nil?
      query_params[:'isPaid'] = opts[:'is_paid'] if !opts[:'is_paid'].nil?
      query_params[:'paymentTypes'] = opts[:'payment_types'] if !opts[:'payment_types'].nil?
      query_params[:'merchantId'] = opts[:'merchant_id'] if !opts[:'merchant_id'].nil?
      query_params[:'paymentCategories'] = opts[:'payment_categories'] if !opts[:'payment_categories'].nil?
      query_params[:'suppressTechnologyFee'] = opts[:'suppress_technology_fee'] if !opts[:'suppress_technology_fee'].nil?
      query_params[:'batchId'] = opts[:'batch_id'] if !opts[:'batch_id'].nil?
      query_params[:'transactionsCount'] = opts[:'transactions_count'] if !opts[:'transactions_count'].nil?
      query_params[:'sortField'] = opts[:'sort_field'] if !opts[:'sort_field'].nil?
      query_params[:'startRow'] = opts[:'start_row'] if !opts[:'start_row'].nil?
      query_params[:'pageSize'] = opts[:'page_size'] if !opts[:'page_size'].nil?
      query_params[:'asc'] = opts[:'asc'] if !opts[:'asc'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'x-api-key'] = x_api_key
      header_params[:'x-app-key'] = x_app_key
      header_params[:'x-version'] = x_version
      header_params[:'origin'] = origin

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'MerchantTransactionEntityResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"SecurePaymentsApi.secure_payments_search_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SecurePaymentsApi#secure_payments_search_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # This API is used for getting details of Payments
    # @param x_api_key [String] an authorization header
    # @param x_app_key [String] an authorization header
    # @param x_version [Float] x-version
    # @param origin [String] origin
    # @param secure_payment_details_request [SecurePaymentDetailsRequest] Payment Details Request
    # @param [Hash] opts the optional parameters
    # @return [TransactionPaymentResponse]
    def secure_paymentsdetails_post(x_api_key, x_app_key, x_version, origin, secure_payment_details_request, opts = {})
      data, _status_code, _headers = secure_paymentsdetails_post_with_http_info(x_api_key, x_app_key, x_version, origin, secure_payment_details_request, opts)
      data
    end

    # This API is used for getting details of Payments
    # @param x_api_key [String] an authorization header
    # @param x_app_key [String] an authorization header
    # @param x_version [Float] x-version
    # @param origin [String] origin
    # @param secure_payment_details_request [SecurePaymentDetailsRequest] Payment Details Request
    # @param [Hash] opts the optional parameters
    # @return [Array<(TransactionPaymentResponse, Integer, Hash)>] TransactionPaymentResponse data, response status code and response headers
    def secure_paymentsdetails_post_with_http_info(x_api_key, x_app_key, x_version, origin, secure_payment_details_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SecurePaymentsApi.secure_paymentsdetails_post ...'
      end
      # verify the required parameter 'x_api_key' is set
      if @api_client.config.client_side_validation && x_api_key.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_key' when calling SecurePaymentsApi.secure_paymentsdetails_post"
      end
      # verify the required parameter 'x_app_key' is set
      if @api_client.config.client_side_validation && x_app_key.nil?
        fail ArgumentError, "Missing the required parameter 'x_app_key' when calling SecurePaymentsApi.secure_paymentsdetails_post"
      end
      # verify the required parameter 'x_version' is set
      if @api_client.config.client_side_validation && x_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_version' when calling SecurePaymentsApi.secure_paymentsdetails_post"
      end
      # verify the required parameter 'origin' is set
      if @api_client.config.client_side_validation && origin.nil?
        fail ArgumentError, "Missing the required parameter 'origin' when calling SecurePaymentsApi.secure_paymentsdetails_post"
      end
      # verify the required parameter 'secure_payment_details_request' is set
      if @api_client.config.client_side_validation && secure_payment_details_request.nil?
        fail ArgumentError, "Missing the required parameter 'secure_payment_details_request' when calling SecurePaymentsApi.secure_paymentsdetails_post"
      end
      # resource path
      local_var_path = '/secure/paymentsdetails'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'x-api-key'] = x_api_key
      header_params[:'x-app-key'] = x_app_key
      header_params[:'x-version'] = x_version
      header_params[:'origin'] = origin

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(secure_payment_details_request)

      # return_type
      return_type = opts[:debug_return_type] || 'TransactionPaymentResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"SecurePaymentsApi.secure_paymentsdetails_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SecurePaymentsApi#secure_paymentsdetails_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
